import {
  APP_ROUTES,
  ROUTE_ANCHORS,
  buildRegionAtlasGamePath,
} from "@/constants/app-config";

export const ARCHIVE_COPY = {
  metadata: {
    title: "Genso Chronicle",
    description: "환상수호전 1, 2의 인물, 문장, 지역, 연표를 정리한 전문 아카이브입니다.",
  },
  header: {
    logoAlt: "Genso Chronicle rune star mark",
    brandName: "Genso Chronicle",
    brandKicker: "Suikoden Reference Wiki",
    searchLabel: "Search Genso Chronicle",
    searchPlaceholder: "Search Characters...",
    searchButton: "Search",
    menuLabel: "Open Navigation",
    closeMenuLabel: "Close Navigation",
    navigationTitle: "Navigation",
    themeToggle: {
      darkLabel: "Switch to dark mode",
      lightLabel: "Switch to light mode",
    },
  },
  sidebar: {
    title: "Library of Destiny",
    subtitle: "Royal Librarian Access",
  },
  hero: {
    title: "Genso Chronicle",
    imageAlt: "Suikoden I and II HD Remaster key visual",
  },
  featured: {
    eyebrow: "Featured Index",
    title: "Featured Articles",
    viewAll: "View All Articles",
  },
  explore: {
    title: "Explore the Wiki",
  },
  news: {
    title: "Wiki News & Announcements",
  },
  stats: {
    title: "Wiki Stats",
    founded: "Founded Dec 5, 2005",
    markAlt: "Genso Chronicle rune star mark",
  },
  quote: {
    body: "Even if things did not turn out the way you wanted them to, you simply have to accept them and move on.",
    author: "Georg Prime",
  },
  trending: {
    title: "Trending Stars",
  },
} as const;

export const IMAGE_PATHS = {
  logoMark: "/suikoden/genso-mark.svg",
  hdRemaster: "/suikoden/hd-remaster.png",
  suikodenI: "/suikoden/suikoden-i.webp",
  suikodenII: "/suikoden/suikoden-ii.webp",
  suikodenRemaster: "/suikoden/suikoden-i-ii-remaster.webp",
  worldMap: "/suikoden/genso-world-guide-map-current.jpg",
} as const;

export const IMAGE_SIZES = {
  logoMark: { width: 44, height: 44 },
  statMark: { width: 44, height: 44 },
} as const;

export const NAV_GROUPS = [
  {
    label: "Series",
    href: APP_ROUTES.home,
    items: [
      { label: "Series Overview", href: APP_ROUTES.home },
      { label: "Historical Timeline", href: ROUTE_ANCHORS.current },
    ],
  },
  {
    label: "Characters",
    href: ROUTE_ANCHORS.current,
    items: [
      { label: "Character Index", href: ROUTE_ANCHORS.current },
      { label: "108 Stars", href: ROUTE_ANCHORS.current },
    ],
  },
  {
    label: "Runes",
    href: ROUTE_ANCHORS.current,
    items: [
      { label: "Rune Index", href: ROUTE_ANCHORS.current },
      { label: "True Runes", href: ROUTE_ANCHORS.current },
    ],
  },
  {
    label: "World Map",
    href: APP_ROUTES.worldMap,
    items: [
      { label: "World Map", href: APP_ROUTES.worldMap },
      { label: "Region Atlas", href: APP_ROUTES.regionAtlas },
      { label: "Suikoden I Regions", href: buildRegionAtlasGamePath("suikoden-i") },
      { label: "Suikoden II Regions", href: buildRegionAtlasGamePath("suikoden-ii") },
    ],
  },
] as const;

export const FEATURE_CARDS = [
  {
    title: "Suikoden I",
    eyebrow: "Gate Rune War",
    image: IMAGE_PATHS.suikodenI,
    alt: "Suikoden I key visual crop",
    body: "Toran Liberation Army, Scarlet Moon Empire, Soul Eater와 108성의 흐름을 정리합니다.",
  },
  {
    title: "Suikoden II",
    eyebrow: "Dunan Unification War",
    image: IMAGE_PATHS.suikodenII,
    alt: "Suikoden II key visual crop",
    body: "State Army와 Highland Kingdom의 전쟁, Bright Shield Rune, 주요 동료 기록을 모읍니다.",
  },
  {
    title: "Suikoden I & II HD Remaster",
    eyebrow: "Core Collection",
    image: IMAGE_PATHS.suikodenRemaster,
    alt: "Suikoden I and II HD Remaster key art",
    body: "두 작품의 리마스터 기준으로 인물, 문장, 지역, 전투 시스템을 연결해 탐색합니다.",
  },
] as const;

export const ARCHIVE_CATEGORIES = [
  { title: "Characters", icon: "users", href: ROUTE_ANCHORS.current, body: "주요 인물, 108성, 동료 영입 조건" },
  { title: "Runes", icon: "sparkles", href: ROUTE_ANCHORS.current, body: "27개의 진정한 문장과 일반 문장 계보" },
  { title: "Locations", icon: "compass", href: APP_ROUTES.regionAtlas, body: "Toran, Dunan, Highland 지역 기록" },
  { title: "Timeline", icon: "history", href: ROUTE_ANCHORS.current, body: "전쟁, 왕조, 국가 변천 연표" },
  { title: "Items", icon: "archive", href: ROUTE_ANCHORS.current, body: "무기, 방어구, 희귀 수집품" },
  { title: "Gameplay", icon: "swords", href: ROUTE_ANCHORS.current, body: "전투, 일기토, 전쟁 시스템" },
] as const;

export const TIMELINE_ITEMS = [
  {
    date: "Mar 06, 2025",
    title: "HD Remaster Released",
    body: "Suikoden I & II HD Remaster가 출시되며 시리즈 입문 동선이 다시 열렸습니다.",
    tag: "Release",
  },
  {
    date: "Dec 17, 1998",
    title: "Suikoden II Released",
    body: "Dunan Unification War를 중심으로 1편의 세계관을 확장한 두 번째 본편 기록입니다.",
    tag: "Game II",
  },
  {
    date: "Dec 15, 1995",
    title: "Suikoden I Released",
    body: "Gate Rune War와 108 Stars of Destiny의 기본 구조가 시작된 첫 번째 본편입니다.",
    tag: "Game I",
  },
] as const;

export const ARCHIVE_STATS = [
  { label: "Referenced Pages", value: "8,355" },
  { label: "Known Files", value: "14,358" },
  { label: "True Runes", value: "27" },
] as const;

export const TRENDING_STARS = ["Tir McDohl", "Riou", "Luc", "Jeane", "Chris"] as const;

export const REGION_ATLAS_COPY = {
  eyebrow: "Region Atlas",
  title: "Region Atlas",
  body: "환상수호전 1, 2의 주요 지역을 작품별 전쟁 무대와 정치권 기준으로 나누어 정리합니다.",
  quickNavTitle: "Quick Nav",
  detailsTitle: "Region Profile",
  locationsLabel: "Key Locations",
  rulingLabel: "Ruling Power",
  runeLabel: "Rune Influence",
  statusLabel: "Status",
  logTitle: "Explorer's Log",
} as const;

export const REGION_PROFILE_FIELDS = [
  { key: "status", label: REGION_ATLAS_COPY.statusLabel },
  { key: "ruling", label: REGION_ATLAS_COPY.rulingLabel },
  { key: "rune", label: REGION_ATLAS_COPY.runeLabel },
] as const;

export const WORLD_MAP_COPY = {
  eyebrow: "World Map",
  title: "World Map",
  body: "시리즈의 주요 무대를 대륙과 권역 기준으로 정리합니다. Toran, Dunan, Grassland, Island Nations처럼 작품별 전쟁과 여정이 펼쳐지는 지역을 한눈에 확인할 수 있습니다.",
  mapAlt: "Genso Chronicle world map showing the major Suikoden stage regions",
  detailCta: "View Full Region Entry",
} as const;

export const WORLD_STAGE_MARKERS = [
  {
    label: "Suikoden I",
    subLabel: "Gate Rune War",
    href: buildRegionAtlasGamePath("suikoden-i"),
    isActive: true,
    x: "75%",
    y: "43%",
    tone: "gold",
  },
  {
    label: "Suikoden II",
    subLabel: "Dunan Unification War",
    href: buildRegionAtlasGamePath("suikoden-ii"),
    isActive: true,
    x: "70%",
    y: "29%",
    tone: "jade",
  },
  {
    label: "Suikoden III",
    subLabel: "Grassland Conflict",
    href: null,
    isActive: false,
    x: "52%",
    y: "16%",
    tone: "sage",
  },
  {
    label: "Suikoden IV",
    subLabel: "Island Nations",
    href: null,
    isActive: false,
    x: "76%",
    y: "62%",
    tone: "amber",
  },
  {
    label: "Suikoden V",
    subLabel: "Falena Queendom",
    href: null,
    isActive: false,
    x: "76%",
    y: "91%",
    tone: "copper",
  },
] as const;

export const REGION_ATLAS_TABS = [
  {
    id: "suikoden-i",
    eyebrow: "Gate Rune War",
    title: "Suikoden I",
    body: "Scarlet Moon Empire에서 Toran Liberation Army로 이어지는 여정의 주요 도시, 요새, 성채를 정리합니다.",
  },
  {
    id: "suikoden-ii",
    eyebrow: "Dunan Unification War",
    title: "Suikoden II",
    body: "Jowston City-State, Highland Kingdom, Matilda Knightdom을 중심으로 Dunan 전쟁의 지역 흐름을 정리합니다.",
  },
] as const;

export const REGION_ATLAS_LOCATIONS = [
  {
    id: "toran-republic",
    game: "suikoden-i",
    name: "Toran Republic",
    category: "Regional Overview",
    status: "Post-Empire Republic",
    ruling: "Toran Liberation Army",
    rune: "Soul Eater / Sovereign Rune",
    description: "Scarlet Moon Empire의 붕괴 이후 성립하는 1편의 핵심 정치권입니다. 호수와 성채를 중심으로 해방군의 전선이 확장됩니다.",
    locations: ["Gregminster", "Toran Castle", "Kaku", "Pannu Yakuta"],
    traits: ["Gate Rune War의 전체 무대", "제국 수도와 해방군 본거지가 함께 위치", "1편의 주요 이동 동선을 포괄"],
    detailHref: "/region-atlas/suikoden-i/toran-republic",
  },
  {
    id: "gregminster",
    game: "suikoden-i",
    name: "Gregminster",
    category: "Capital",
    status: "Imperial Capital",
    ruling: "Scarlet Moon Empire",
    rune: "Sovereign Rune",
    description: "Scarlet Moon Empire의 수도이자 주인공의 여정이 시작되는 중심 도시입니다. 제국 권력과 해방군의 최종 목표가 교차합니다.",
    locations: ["McDohl Residence", "Imperial Palace", "Gregminster Gate"],
    traits: ["초반 제국 임무의 출발점", "Barbarossa와 Windy의 권력 중심", "Gate Rune War의 종착지"],
    detailHref: "/region-atlas/suikoden-i/gregminster",
  },
  {
    id: "lenankamp",
    game: "suikoden-i",
    name: "Lenankamp",
    category: "Town",
    status: "Imperial Territory",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "초반 여정에서 제국의 통치 구조와 민심을 확인하게 되는 도시입니다. 해방군과 제국의 긴장이 본격적으로 드러납니다.",
    locations: ["Lenankamp Inn", "Town Square"],
    traits: ["초반 동료와 사건이 모이는 거점", "제국 감시망의 압박이 드러나는 도시", "Toran 남부 이동 동선의 관문"],
    detailHref: "/region-atlas/suikoden-i/lenankamp",
  },
  {
    id: "rockland",
    game: "suikoden-i",
    name: "Rockland",
    category: "Town",
    status: "Imperial Territory",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "제국 지방 통치의 부패와 압박을 보여주는 초반 지역입니다. 주인공 일행이 민심의 균열을 직접 확인하는 구역입니다.",
    locations: ["Rockland Town", "Mt. Seifu Route"],
    traits: ["초반 임무와 산적 사건의 중심", "지방 행정의 부패가 부각", "Mt. Seifu로 이어지는 이동 거점"],
    detailHref: "/region-atlas/suikoden-i/rockland",
  },
  {
    id: "sarady",
    game: "suikoden-i",
    name: "Sarady",
    category: "Village",
    status: "Remote Settlement",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "제국 북부 산악 지대의 작은 마을입니다. 초반 임무에서 외곽 지역의 폐쇄성과 제국의 영향권을 함께 보여줍니다.",
    locations: ["Sarady Village", "Northern Mountain Path"],
    traits: ["초반 북부 이동의 끝점", "외곽 마을 특유의 고립감", "제국 영토의 넓이를 체감시키는 장소"],
    detailHref: "/region-atlas/suikoden-i/sarady",
  },
  {
    id: "kaku",
    game: "suikoden-i",
    name: "Kaku",
    category: "Port Town",
    status: "Lake Toran Port",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "Lake Toran을 통한 이동과 해방군 본거지 확보로 이어지는 항구 도시입니다. 1편의 수상 교통 동선이 시작되는 곳입니다.",
    locations: ["Kaku Port", "Lake Toran Ferry"],
    traits: ["수상 이동의 출발점", "Toran Castle 접근의 관문", "도박장과 항구 문화가 공존"],
    detailHref: "/region-atlas/suikoden-i/kaku",
  },
  {
    id: "kouan",
    game: "suikoden-i",
    name: "Kouan",
    category: "Town",
    status: "Imperial Territory",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "Lepant의 저택과 연결되는 도시입니다. 지방 유력자의 정치적 태도와 해방군 합류의 흐름을 보여줍니다.",
    locations: ["Lepant Mansion", "Kouan Town"],
    traits: ["Lepant 관련 사건의 중심", "지방 명사와 해방군의 연결점", "초중반 전력 확장의 계기"],
    detailHref: "/region-atlas/suikoden-i/kouan",
  },
  {
    id: "seika",
    game: "suikoden-i",
    name: "Seika",
    category: "Town",
    status: "Academy Town",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "Mathiu Silverberg와 연결되는 전략적 전환점입니다. 해방군이 단순 저항 세력에서 조직화된 군대로 바뀌는 계기가 됩니다.",
    locations: ["Mathiu's School", "Seika Town"],
    traits: ["해방군 전략 체계의 출발점", "Mathiu 영입과 연결", "전쟁 규모가 확장되는 분기점"],
    detailHref: "/region-atlas/suikoden-i/seika",
  },
  {
    id: "great-forest",
    game: "suikoden-i",
    name: "Great Forest",
    category: "Forest Region",
    status: "Forest Territory",
    ruling: "Forest Communities",
    rune: "None Recorded",
    description: "엘프, 드워프, 코볼트 거주지가 얽힌 광대한 숲 지역입니다. 제국 전쟁이 비인간 종족권까지 확장되는 구역입니다.",
    locations: ["Elf Village", "Dwarf Village", "Kobold Village"],
    traits: ["여러 종족권이 공존", "Burning Mirror 사건과 연결", "중반 전쟁의 주요 비극이 발생"],
    detailHref: "/region-atlas/suikoden-i/great-forest",
  },
  {
    id: "dwarf-village",
    game: "suikoden-i",
    name: "Dwarf Village",
    category: "Settlement",
    status: "Dwarven Settlement",
    ruling: "Dwarven Community",
    rune: "None Recorded",
    description: "Great Forest 안쪽의 드워프 거점입니다. 장인 문화와 군사 기술, 종족 간 갈등의 흐름이 함께 드러납니다.",
    locations: ["Dwarf Vault", "Dwarf Trail"],
    traits: ["Great Forest 사건의 핵심 거점", "제국의 병기 위협과 연결", "종족권 정치가 드러나는 마을"],
    detailHref: "/region-atlas/suikoden-i/dwarf-village",
  },
  {
    id: "antei",
    game: "suikoden-i",
    name: "Antei",
    category: "Town",
    status: "Lake Region Town",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "Lake Toran 주변 이동망에 속한 도시입니다. 해방군이 남부와 호수권을 오가며 세력을 넓히는 과정에 놓입니다.",
    locations: ["Antei Town", "Lake Road"],
    traits: ["호수권 이동 동선의 일부", "중반 탐색 루트와 연결", "주변 도시와 함께 생활권을 형성"],
    detailHref: "/region-atlas/suikoden-i/antei",
  },
  {
    id: "teien",
    game: "suikoden-i",
    name: "Teien",
    category: "Town",
    status: "Lake Region Town",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "Lake Toran 남부권의 도시입니다. Rikon, Antei와 함께 1편의 호수 남부 생활권을 구성합니다.",
    locations: ["Teien Town", "Lake Toran South"],
    traits: ["호수 남부 탐색의 중간 지점", "인접 도시와 연결된 생활권", "전쟁 중반 이동 루트"],
    detailHref: "/region-atlas/suikoden-i/teien",
  },
  {
    id: "rikon",
    game: "suikoden-i",
    name: "Rikon",
    category: "Town",
    status: "Lake Region Town",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "Lake Toran 남단에 위치한 도시입니다. Liukan 관련 동선과 연결되며 해방군의 치료와 정보 흐름에 관여합니다.",
    locations: ["Rikon Town", "Liukan's Hermitage Route"],
    traits: ["Liukan 관련 동선과 연결", "호수권 남부의 끝점", "중반 전력 회복의 단서"],
    detailHref: "/region-atlas/suikoden-i/rikon",
  },
  {
    id: "toran-castle",
    game: "suikoden-i",
    name: "Toran Castle",
    category: "Headquarters",
    status: "Liberation Army Base",
    ruling: "Toran Liberation Army",
    rune: "None Recorded",
    description: "해방군의 본거지입니다. 108성의 합류와 군사 조직 확장이 모두 이 성을 중심으로 진행됩니다.",
    locations: ["Castle Hall", "Lake Toran"],
    traits: ["해방군 본부", "동료 영입에 따라 확장", "전쟁 지휘와 생활 기능이 결합"],
    detailHref: "/region-atlas/suikoden-i/toran-castle",
  },
  {
    id: "pannu-yakuta",
    game: "suikoden-i",
    name: "Pannu Yakuta",
    category: "Fortress",
    status: "Imperial Fortress",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "제국군의 핵심 요새 중 하나입니다. 해방군과 제국군의 정면 충돌이 본격화되는 전략 거점입니다.",
    locations: ["Pannu Yakuta Fortress"],
    traits: ["제국 방어선의 주요 축", "대규모 충돌이 벌어지는 요새", "Gate Rune War 후반부로 이어지는 관문"],
    detailHref: "/region-atlas/suikoden-i/pannu-yakuta",
  },
  {
    id: "shasarazade",
    game: "suikoden-i",
    name: "Shasarazade",
    category: "Fortress",
    status: "Imperial Naval Fortress",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "제국의 수상 방어 거점입니다. Gregminster로 향하는 최종 전선에서 해방군의 진격을 가로막습니다.",
    locations: ["Shasarazade Fortress", "Lake Passage"],
    traits: ["최종전 직전의 수상 요새", "제국 수도 접근로 통제", "해방군 진격의 마지막 관문 중 하나"],
    detailHref: "/region-atlas/suikoden-i/shasarazade",
  },
  {
    id: "moravia-castle",
    game: "suikoden-i",
    name: "Moravia Castle",
    category: "Castle",
    status: "Imperial Stronghold",
    ruling: "Scarlet Moon Empire",
    rune: "None Recorded",
    description: "제국 북방권의 성채입니다. 인물 구출과 후반부 전선 확장에 연결되는 전략 지점입니다.",
    locations: ["Moravia Castle", "Northern Route"],
    traits: ["후반부 침투 동선", "제국 북방 방어망의 일부", "중요 인물 구출과 연결"],
    detailHref: "/region-atlas/suikoden-i/moravia-castle",
  },
  {
    id: "jowston-city-state",
    game: "suikoden-ii",
    name: "Jowston City-State",
    category: "Regional Overview",
    status: "City-State Alliance",
    ruling: "Jowston Council",
    rune: "Bright Shield Rune",
    description: "Muse, South Window, Two River, Greenhill 등이 얽힌 도시국가 연합입니다. Dunan Unification War의 정치적 중심축입니다.",
    locations: ["Muse", "South Window", "Two River", "Greenhill"],
    traits: ["도시국가 간 이해관계가 복잡", "Dunan 전쟁의 외교적 중심", "Highland 침공의 주요 대상"],
    detailHref: "/region-atlas/suikoden-ii/jowston-city-state",
  },
  {
    id: "highland-kingdom",
    game: "suikoden-ii",
    name: "Highland Kingdom",
    category: "Regional Overview",
    status: "Northern Monarchy",
    ruling: "House Blight",
    rune: "Black Sword Rune",
    description: "L'Renouille을 수도로 하는 북방 왕국입니다. 2편의 전쟁을 촉발한 군사 국가이자 Jowston의 가장 큰 적대 세력입니다.",
    locations: ["L'Renouille", "Kyaro", "Sajah", "Tenzan Pass"],
    traits: ["왕권 중심 군사 국가", "Dunan Unification War의 침공 세력", "국경 요새와 산악로 장악"],
    detailHref: "/region-atlas/suikoden-ii/highland-kingdom",
  },
  {
    id: "matilda-knightdom",
    game: "suikoden-ii",
    name: "Matilda Knightdom",
    category: "Regional Overview",
    status: "Knightdom",
    ruling: "Knights of Matilda",
    rune: "None Recorded",
    description: "Rockaxe를 중심으로 한 기사단 국가입니다. Dunan 북서부의 전략 요충지로 전쟁의 균형을 흔드는 지역입니다.",
    locations: ["Rockaxe", "Highway Village", "Matilda Path"],
    traits: ["기사단 전통과 봉건적 질서", "Jowston과 Highland 사이의 완충 지대", "전쟁 국면에 따라 입장이 흔들리는 세력권"],
    detailHref: "/region-atlas/suikoden-ii/matilda-knightdom",
  },
  {
    id: "muse",
    game: "suikoden-ii",
    name: "Muse",
    category: "City-State",
    status: "Jowston Capital",
    ruling: "Muse City-State",
    rune: "None Recorded",
    description: "Jowston City-State의 정치 중심지입니다. 동맹 회의와 Highland 침공의 충격이 집중되는 도시입니다.",
    locations: ["Muse City", "Jowston Hill"],
    traits: ["Jowston 의회의 중심", "Dunan 전쟁 초중반의 핵심 무대", "도시국가 연합의 취약성이 드러나는 장소"],
    detailHref: "/region-atlas/suikoden-ii/muse",
  },
  {
    id: "greenhill",
    game: "suikoden-ii",
    name: "Greenhill",
    category: "City-State",
    status: "Academy City",
    ruling: "Greenhill City-State",
    rune: "None Recorded",
    description: "학원 도시로 알려진 Jowston의 주요 도시국가입니다. 점령과 잠입, 학생 사회의 시선이 함께 그려집니다.",
    locations: ["Greenhill Academy", "Forest Village Route"],
    traits: ["학원 도시의 정체성", "Highland 점령과 저항의 무대", "잠입 서사가 중심이 되는 지역"],
    detailHref: "/region-atlas/suikoden-ii/greenhill",
  },
  {
    id: "two-river",
    game: "suikoden-ii",
    name: "Two River",
    category: "City-State",
    status: "Multi-District City",
    ruling: "Two River City-State",
    rune: "None Recorded",
    description: "인간, 코볼트, 윙거 구역이 나뉜 도시국가입니다. 종족 간 갈등과 도시 방어가 중요한 축으로 등장합니다.",
    locations: ["Human District", "Kobold District", "Winger District"],
    traits: ["다종족 도시 구조", "도시 방어전의 중심", "Jowston 내부 갈등을 보여주는 장소"],
    detailHref: "/region-atlas/suikoden-ii/two-river",
  },
  {
    id: "south-window",
    game: "suikoden-ii",
    name: "South Window",
    category: "City-State",
    status: "Southern City-State",
    ruling: "South Window City-State",
    rune: "None Recorded",
    description: "Jowston 남부의 주요 도시국가입니다. North Window, Radat, Kuskus와 함께 남부 동선을 이룹니다.",
    locations: ["South Window City", "North Window Route"],
    traits: ["Jowston 남부 정치권", "초중반 이동 동선의 중심", "주변 항구와 강길로 연결"],
    detailHref: "/region-atlas/suikoden-ii/south-window",
  },
  {
    id: "rockaxe",
    game: "suikoden-ii",
    name: "Rockaxe",
    category: "Castle Town",
    status: "Matilda Capital",
    ruling: "Knights of Matilda",
    rune: "None Recorded",
    description: "Matilda Knightdom의 중심 성채 도시입니다. 기사단의 질서와 Dunan 전쟁의 정치적 선택이 집중됩니다.",
    locations: ["Rockaxe Castle", "Matilda Path"],
    traits: ["Matilda 기사단의 중심", "Jowston 북서부 방어의 핵심", "전쟁 후반 선택의 무게가 큰 도시"],
    detailHref: "/region-atlas/suikoden-ii/rockaxe",
  },
  {
    id: "lrnouille",
    game: "suikoden-ii",
    name: "L'Renouille",
    category: "Capital",
    status: "Highland Capital",
    ruling: "Highland Kingdom",
    rune: "Black Sword Rune",
    description: "Highland Kingdom의 수도입니다. Dunan Unification War의 최종 국면이 향하는 왕권의 중심지입니다.",
    locations: ["Royal Palace", "Highland Capital"],
    traits: ["Highland 왕권의 중심", "전쟁 후반부의 최종 목표", "Black Sword Rune의 정치적 상징과 연결"],
    detailHref: "/region-atlas/suikoden-ii/lrnouille",
  },
] as const;

export const REGION_ATLAS_LOGS = [
  {
    title: "Gate Rune War Campaign",
    body: "Toran 남부의 항구와 성채를 거쳐 Gregminster로 향하는 동선은 1편의 해방군 성장 과정을 따라갑니다.",
    icon: "book",
  },
  {
    title: "Dunan Border Pressure",
    body: "Highland와 Jowston 사이의 국경 지대는 2편의 전쟁 사건이 집중되는 핵심 축입니다.",
    icon: "compass",
  },
] as const;
