import {
  buildRuneCategoryPath,
  buildRuneDetailPath,
} from "@/constants/app-config";

export const RUNE_ARCHIVE_COPY = {
  eyebrow: "Runes",
  title: "Runes",
  body: "일반 문장과 27개의 진정한 문장을 작품별 기록과 연결해 정리합니다.",
  generalTitle: "General Runes",
  generalEyebrow: "일반 문장",
  generalBody:
    "전투, 마법, 이동, 고유 기술에 연결되는 일반 문장과 고유 문장을 함께 정리합니다.",
  trueTitle: "True Runes",
  trueEyebrow: "진정한 문장",
  trueBody:
    "27개의 진정한 문장을 공개된 실명 문장과 미공개 문장까지 함께 정리합니다.",
  profileTitle: "Rune Profile",
  categoryLabel: "구분",
  gamesLabel: "등장 작품",
  aliasLabel: "표기",
  searchLabel: "Rune search",
  searchPlaceholder: "문장 이름, 영문 표기, 등장 작품 검색",
  resultCount: (count: number) => `${count.toLocaleString("ko-KR")}개 문장`,
  noResults: "검색 조건에 맞는 문장이 없습니다.",
  unavailableDetail: "-",
  ariaLabels: {
    categoryTabs: "Rune categories",
  },
} as const;

export const RUNE_CATEGORY_LABELS = {
  trueRune: "진정한 문장",
  generalRune: "일반 문장",
  uniqueRune: "고유 문장",
} as const;

export type RuneCategoryId = keyof typeof RUNE_CATEGORY_LABELS;

export const RUNE_INDEX_PAGE_IDS = {
  general: "general",
  true: "true",
} as const;

export type RuneIndexPageId =
  (typeof RUNE_INDEX_PAGE_IDS)[keyof typeof RUNE_INDEX_PAGE_IDS];

export const RUNE_INDEX_PAGES = [
  {
    id: RUNE_INDEX_PAGE_IDS.general,
    href: buildRuneCategoryPath(RUNE_INDEX_PAGE_IDS.general),
    title: RUNE_ARCHIVE_COPY.generalTitle,
    eyebrow: RUNE_ARCHIVE_COPY.generalEyebrow,
    body: RUNE_ARCHIVE_COPY.generalBody,
    categories: ["generalRune", "uniqueRune"],
  },
  {
    id: RUNE_INDEX_PAGE_IDS.true,
    href: buildRuneCategoryPath(RUNE_INDEX_PAGE_IDS.true),
    title: RUNE_ARCHIVE_COPY.trueTitle,
    eyebrow: RUNE_ARCHIVE_COPY.trueEyebrow,
    body: RUNE_ARCHIVE_COPY.trueBody,
    categories: ["trueRune"],
  },
] as const satisfies readonly {
  id: RuneIndexPageId;
  href: string;
  title: string;
  eyebrow: string;
  body: string;
  categories: readonly RuneCategoryId[];
}[];

export type RuneReference = {
  id: string;
  name: string;
  aliases: readonly string[];
  category: RuneCategoryId;
  games: readonly string[];
  imageSrc?: string;
  href: string;
};

export const RUNE_GAME_LABELS = {
  "suikoden-i": "환상수호전 I",
  "suikoden-ii": "환상수호전 II",
  "suikoden-iii": "환상수호전 III",
  "suikoden-iv": "환상수호전 IV",
  "suikoden-v": "환상수호전 V",
  "suikoden-tactics": "환상수호전 택틱스",
  unrevealed: "미공개",
} as const;

export const RUNE_TRUE_RUNE_IMAGE = {
  src: "/suikoden/runes/the-27-true-runes.jpg",
  alt: "27개의 진정한 문장 도해",
} as const;

const buildRuneReference = (
  rune: Omit<RuneReference, "href">,
): RuneReference => {
  return {
    ...rune,
    href: buildRuneDetailPath(rune.id),
  };
};

export const RUNE_REFERENCES = [
  buildRuneReference({
    id: "soul-eater",
    name: "소울이터",
    aliases: ["Soul Eater"],
    category: "trueRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/soul-eater.png",
  }),
  buildRuneReference({
    id: "bright-shield-rune",
    name: "빛나는 방패의 문장",
    aliases: ["Bright Shield Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/bright-shield-rune.png",
  }),
  buildRuneReference({
    id: "black-sword-rune",
    name: "검은 검의 문장",
    aliases: ["Black Sword Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/black-sword-rune.png",
  }),
  buildRuneReference({
    id: "rune-of-beginning",
    name: "시작의 문장",
    aliases: ["Rune of Beginning"],
    category: "trueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/rune-of-beginning.png",
  }),
  buildRuneReference({
    id: "rune-of-change",
    name: "변화의 문장",
    aliases: ["Rune of Change"],
    category: "trueRune",
    games: ["unrevealed"],
    imageSrc: "/suikoden/runes/rune-of-change.png",
  }),
  buildRuneReference({
    id: "rune-of-punishment",
    name: "벌의 문장",
    aliases: ["Rune of Punishment"],
    category: "trueRune",
    games: ["suikoden-iv", "suikoden-tactics"],
    imageSrc: "/suikoden/runes/rune-of-punishment.png",
  }),
  buildRuneReference({
    id: "blue-moon-rune",
    name: "푸른 달의 문장",
    aliases: ["Blue Moon Rune", "Moon Rune"],
    category: "trueRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/blue-moon-rune.png",
  }),
  buildRuneReference({
    id: "sovereign-rune",
    name: "패왕의 문장",
    aliases: ["Sovereign Rune"],
    category: "trueRune",
    games: ["suikoden-i"],
  }),
  buildRuneReference({
    id: "fire-rune",
    name: "불의 문장",
    aliases: ["Fire Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/fire-rune.png",
  }),
  buildRuneReference({
    id: "water-rune",
    name: "물의 문장",
    aliases: ["Water Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/water-rune.png",
  }),
  buildRuneReference({
    id: "wind-rune",
    name: "바람의 문장",
    aliases: ["Wind Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/wind-rune.png",
  }),
  buildRuneReference({
    id: "lightning-rune",
    name: "번개의 문장",
    aliases: ["Lightning Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/lightning-rune.png",
  }),
  buildRuneReference({
    id: "thunder-rune",
    name: "천둥의 문장",
    aliases: ["Thunder Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/thunder-rune.png",
  }),
  buildRuneReference({
    id: "rage-rune",
    name: "분노의 문장",
    aliases: ["Rage Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/rage-rune.png",
  }),
  buildRuneReference({
    id: "flowing-rune",
    name: "흐르는 문장",
    aliases: ["Flowing Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/flowing-rune.png",
  }),
  buildRuneReference({
    id: "earth-rune",
    name: "대지의 문장",
    aliases: ["Earth Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/earth-rune.png",
  }),
  buildRuneReference({
    id: "mother-earth-rune",
    name: "모대지의 문장",
    aliases: ["Mother Earth Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/mother-earth-rune.png",
  }),
  buildRuneReference({
    id: "resurrection-rune",
    name: "부활의 문장",
    aliases: ["Resurrection Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/resurrection-rune.png",
  }),
  buildRuneReference({
    id: "blue-gate-rune",
    name: "창문의 문장",
    aliases: ["Blue Gate Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/blue-gate-rune.png",
  }),
  buildRuneReference({
    id: "darkness-rune",
    name: "어둠의 문장",
    aliases: ["Darkness Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/darkness-rune.png",
  }),
  buildRuneReference({
    id: "cyclone-rune",
    name: "선풍의 문장",
    aliases: ["Cyclone Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/cyclone-rune.png",
  }),
  buildRuneReference({
    id: "killer-rune",
    name: "필살의 문장",
    aliases: ["Killer Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/killer-rune.png",
  }),
  buildRuneReference({
    id: "turtle-rune",
    name: "거북이의 문장",
    aliases: ["Turtle Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/turtle-rune.png",
  }),
  buildRuneReference({
    id: "phero-rune",
    name: "페로의 문장",
    aliases: ["Phero Rune"],
    category: "generalRune",
    games: ["suikoden-i"],
    imageSrc: "/suikoden/runes/phero-rune.png",
  }),
  buildRuneReference({
    id: "fortune-rune",
    name: "행운의 문장",
    aliases: ["Fortune Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/fortune-rune.png",
  }),
  buildRuneReference({
    id: "counter-rune",
    name: "반격의 문장",
    aliases: ["Counter Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/counter-rune.png",
  }),
  buildRuneReference({
    id: "hazy-rune",
    name: "양지의 문장",
    aliases: ["Hazy Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/hazy-rune.png",
  }),
  buildRuneReference({
    id: "holy-rune",
    name: "신행법의 문장",
    aliases: ["Holy Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/holy-rune.png",
  }),
  buildRuneReference({
    id: "true-holy-rune",
    name: "진신행법의 문장",
    aliases: ["True Holy Rune"],
    category: "uniqueRune",
    games: ["suikoden-i"],
    imageSrc: "/suikoden/runes/true-holy-rune.png",
  }),
  buildRuneReference({
    id: "fury-rune",
    name: "분노의 문장",
    aliases: ["Fury Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
  }),
  buildRuneReference({
    id: "double-beat-rune",
    name: "2회공격의 문장",
    aliases: ["Double Beat Rune", "Double-Beat Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/double-beat-rune.gif",
  }),
  buildRuneReference({
    id: "double-strike-rune",
    name: "더블 스트라이크의 문장",
    aliases: ["Double Strike Rune", "Double-Strike Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/double-strike-rune.png",
  }),
  buildRuneReference({
    id: "gale-rune",
    name: "질풍의 문장",
    aliases: ["Gale Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/gale-rune.png",
  }),
  buildRuneReference({
    id: "balance-rune",
    name: "밸런스의 문장",
    aliases: ["Balance Rune"],
    category: "generalRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/balance-rune.png",
  }),
  buildRuneReference({
    id: "spark-rune",
    name: "스파크의 문장",
    aliases: ["Spark Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/spark-rune.png",
  }),
  buildRuneReference({
    id: "warrior-rune",
    name: "전사의 문장",
    aliases: ["Warrior Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/warrior-rune.png",
  }),
  buildRuneReference({
    id: "barrier-rune",
    name: "방벽의 문장",
    aliases: ["Barrier Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "medicine-rune",
    name: "약의 문장",
    aliases: ["Medicine Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "technique-rune",
    name: "기술의 문장",
    aliases: ["Technique Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "clone-rune",
    name: "분신의 문장",
    aliases: ["Clone Rune"],
    category: "generalRune",
    games: ["suikoden-i"],
    imageSrc: "/suikoden/runes/clone-rune.png",
  }),
  buildRuneReference({
    id: "blinking-rune",
    name: "순간이동의 문장",
    aliases: ["Blinking Rune"],
    category: "uniqueRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/blinking-rune.png",
  }),
  buildRuneReference({
    id: "falcon-rune",
    name: "매의 문장",
    aliases: ["Falcon Rune"],
    category: "uniqueRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/falcon-rune.png",
  }),
  buildRuneReference({
    id: "boar-rune",
    name: "멧돼지의 문장",
    aliases: ["Boar Rune"],
    category: "uniqueRune",
    games: ["suikoden-i"],
    imageSrc: "/suikoden/runes/boar-rune.png",
  }),
  buildRuneReference({
    id: "hate-rune",
    name: "증오의 문장",
    aliases: ["Hate Rune"],
    category: "uniqueRune",
    games: ["suikoden-i"],
    imageSrc: "/suikoden/runes/hate-rune.png",
  }),
  buildRuneReference({
    id: "trick-rune",
    name: "장난감의 문장",
    aliases: ["Trick Rune"],
    category: "uniqueRune",
    games: ["suikoden-i", "suikoden-ii"],
    imageSrc: "/suikoden/runes/trick-rune.png",
  }),
  buildRuneReference({
    id: "fire-breath-rune",
    name: "화염방사의 문장",
    aliases: ["Fire Breath Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/fire-breath-rune.gif",
  }),
  buildRuneReference({
    id: "rabid-fang-rune",
    name: "광아의 문장",
    aliases: ["Rabid Fang Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/rabid-fang-rune.gif",
  }),
  buildRuneReference({
    id: "howling-rune",
    name: "포효의 문장",
    aliases: ["Howling Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "great-hawk-rune",
    name: "큰매의 문장",
    aliases: ["Great Hawk Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/great-hawk-rune.png",
  }),
  buildRuneReference({
    id: "shining-wind-rune",
    name: "빛나는 바람의 문장",
    aliases: ["Shining Wind Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "blessed-white-lady-rune",
    name: "축복받은 백부인의 문장",
    aliases: ["Blessed White Lady Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/blessed-white-lady-rune.png",
  }),
  buildRuneReference({
    id: "blue-drop-rune",
    name: "푸른 물방울의 문장",
    aliases: ["Blue Drop Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/blue-drop-rune.gif",
  }),
  buildRuneReference({
    id: "fire-dragon-rune",
    name: "화룡의 문장",
    aliases: ["Fire Dragon Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/fire-dragon-rune.gif",
  }),
  buildRuneReference({
    id: "angry-dragon-rune",
    name: "분노한 용의 문장",
    aliases: ["Angry Dragon Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/angry-dragon-rune.gif",
  }),
  buildRuneReference({
    id: "waking-rune",
    name: "각성의 문장",
    aliases: ["Waking Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/waking-rune.png",
  }),
  buildRuneReference({
    id: "spider-slay-rune",
    name: "거미베기의 문장",
    aliases: ["Spider Slay Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/spider-slay-rune.jpg",
  }),
  buildRuneReference({
    id: "unicorn-rune",
    name: "일각수의 문장",
    aliases: ["Unicorn Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/unicorn-rune.png",
  }),
  buildRuneReference({
    id: "knight-rune",
    name: "기사의 문장",
    aliases: ["Knight Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "shrike-rune",
    name: "때까치의 문장",
    aliases: ["Shrike Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/shrike-rune.png",
  }),
  buildRuneReference({
    id: "mayfly-rune",
    name: "하루살이의 문장",
    aliases: ["Mayfly Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/mayfly-rune.gif",
  }),
  buildRuneReference({
    id: "twin-ring-rune",
    name: "쌍륜의 문장",
    aliases: ["Twin Ring Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/twin-ring-rune.gif",
  }),
  buildRuneReference({
    id: "gadget-rune",
    name: "가젯의 문장",
    aliases: ["Gadget Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/gadget-rune.jpg",
  }),
  buildRuneReference({
    id: "white-tiger-rune",
    name: "백호의 문장",
    aliases: ["White Tiger Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "white-saint-rune",
    name: "백성의 문장",
    aliases: ["White Saint Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/white-saint-rune.png",
  }),
  buildRuneReference({
    id: "swallow-rune",
    name: "제비의 문장",
    aliases: ["Swallow Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "groundhog-rune",
    name: "두더지의 문장",
    aliases: ["Groundhog Rune"],
    category: "uniqueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/groundhog-rune.png",
  }),
  buildRuneReference({
    id: "alert-rune",
    name: "경계의 문장",
    aliases: ["Alert Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/alert-rune.png",
  }),
  buildRuneReference({
    id: "alertness-rune",
    name: "경계의 문장",
    aliases: ["Alertness Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-iv"],
    imageSrc: "/suikoden/runes/alertness-rune.png",
  }),
  buildRuneReference({
    id: "back-gate-rune",
    name: "뒷문의 문장",
    aliases: ["Back Gate Rune"],
    category: "generalRune",
    games: ["suikoden-i","suikoden-iii"],
  }),
  buildRuneReference({
    id: "balloon-rune",
    name: "풍선의 문장",
    aliases: ["Balloon Rune"],
    category: "generalRune",
    games: ["suikoden-tactics"],
  }),
  buildRuneReference({
    id: "banshee-rune",
    name: "밴시의 문장",
    aliases: ["Banshee Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "beast-rune",
    name: "짐승의 문장",
    aliases: ["Beast Rune"],
    category: "trueRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/beast-rune.png",
  }),
  buildRuneReference({
    id: "boost-rune",
    name: "부스트의 문장",
    aliases: ["Boost Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "boronda-hawk-rune",
    name: "보론다 매의 문장",
    aliases: ["Boronda Hawk Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
    imageSrc: "/suikoden/runes/boronda-hawk-rune.jpg",
  }),
  buildRuneReference({
    id: "boundary-rune",
    name: "경계의 문장",
    aliases: ["Boundary Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "bucket-rune",
    name: "양동이의 문장",
    aliases: ["Bucket Rune"],
    category: "generalRune",
    games: ["suikoden-tactics"],
  }),
  buildRuneReference({
    id: "chameleon-rune",
    name: "카멜레온의 문장",
    aliases: ["Chameleon Rune"],
    category: "generalRune",
    games: ["suikoden-tactics"],
  }),
  buildRuneReference({
    id: "champion-s-rune",
    name: "챔피언의 문장",
    aliases: ["Champion's Rune"],
    category: "generalRune",
    games: ["suikoden-i","suikoden-ii","suikoden-iii","suikoden-iv","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/champion-s-rune.png",
  }),
  buildRuneReference({
    id: "charm-rune",
    name: "매혹의 문장",
    aliases: ["Charm Rune"],
    category: "generalRune",
    games: ["suikoden-iv","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/charm-rune.png",
  }),
  buildRuneReference({
    id: "chimera-rune",
    name: "키메라의 문장",
    aliases: ["Chimera Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "circle-rune",
    name: "원환의 문장",
    aliases: ["Circle Rune"],
    category: "trueRune",
    games: ["suikoden-iii"],
    imageSrc: "/suikoden/runes/circle-rune.png",
  }),
  buildRuneReference({
    id: "comet-rune",
    name: "혜성의 문장",
    aliases: ["Comet Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "conqueror-rune",
    name: "정복자의 문장",
    aliases: ["Conqueror Rune"],
    category: "generalRune",
    games: ["suikoden-i"],
  }),
  buildRuneReference({
    id: "crazed-rune",
    name: "광기의 문장",
    aliases: ["Crazed Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "dawn-rune",
    name: "새벽의 문장",
    aliases: ["Dawn Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/dawn-rune.png",
  }),
  buildRuneReference({
    id: "devil-s-doll-rune",
    name: "악마 인형의 문장",
    aliases: ["Devil's Doll Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "doremi-rune",
    name: "도레미의 문장",
    aliases: ["DoReMi Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/doremi-rune.png",
  }),
  buildRuneReference({
    id: "double-tusk-rune",
    name: "쌍아의 문장",
    aliases: ["Double Tusk Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "double-edged-rune",
    name: "양날의 문장",
    aliases: ["Double-Edged Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/double-edged-rune.png",
  }),
  buildRuneReference({
    id: "down-rune",
    name: "다운의 문장",
    aliases: ["Down Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "dragon-rune",
    name: "용의 문장",
    aliases: ["Dragon Rune"],
    category: "trueRune",
    games: ["suikoden-i"],
    imageSrc: "/suikoden/runes/dragon-rune.png",
  }),
  buildRuneReference({
    id: "drain-rune",
    name: "흡수의 문장",
    aliases: ["Drain Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-iv","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/drain-rune.png",
  }),
  buildRuneReference({
    id: "dryad-rune",
    name: "드라이어드의 문장",
    aliases: ["Dryad Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "eagle-rune",
    name: "독수리의 문장",
    aliases: ["Eagle Rune"],
    category: "generalRune",
    games: ["suikoden-tactics"],
  }),
  buildRuneReference({
    id: "eight-devil-rune",
    name: "팔귀의 문장",
    aliases: ["Eight Devil Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "eightfold-rune",
    name: "팔방의 문장",
    aliases: ["Eightfold Rune"],
    category: "trueRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "equilibrium-rune",
    name: "균형의 문장",
    aliases: ["Equilibrium Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/equilibrium-rune.png",
  }),
  buildRuneReference({
    id: "exertion-rune",
    name: "분발의 문장",
    aliases: ["Exertion Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "fierce-tiger-rune",
    name: "맹호의 문장",
    aliases: ["Fierce Tiger Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/fierce-tiger-rune.gif",
  }),
  buildRuneReference({
    id: "fire-lizard-rune",
    name: "불도마뱀의 문장",
    aliases: ["Fire Lizard Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
    imageSrc: "/suikoden/runes/fire-lizard-rune.png",
  }),
  buildRuneReference({
    id: "fire-sealing-rune",
    name: "불 봉인의 문장",
    aliases: ["Fire Sealing Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-v"],
    imageSrc: "/suikoden/runes/fire-sealing-rune.png",
  }),
  buildRuneReference({
    id: "firefly-rune",
    name: "반딧불의 문장",
    aliases: ["Firefly Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-iv","suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "flow-rune",
    name: "흐름의 문장",
    aliases: ["Flow Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "flowing-sword-rune",
    name: "흐르는 검의 문장",
    aliases: ["Flowing Sword Rune"],
    category: "generalRune",
    games: ["suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "friendship-rune",
    name: "우정의 문장",
    aliases: ["Friendship Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "front-gate-rune",
    name: "앞문의 문장",
    aliases: ["Front Gate Rune"],
    category: "generalRune",
    games: ["suikoden-i"],
  }),
  buildRuneReference({
    id: "full-moon-rune",
    name: "보름달의 문장",
    aliases: ["Full Moon Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "gate-rune",
    name: "문의 문장",
    aliases: ["Gate Rune"],
    category: "trueRune",
    games: ["suikoden-i"],
    imageSrc: "/suikoden/runes/gate-rune.png",
  }),
  buildRuneReference({
    id: "giant-owl-rune",
    name: "큰올빼미의 문장",
    aliases: ["Giant Owl Rune"],
    category: "generalRune",
    games: ["suikoden-tactics"],
  }),
  buildRuneReference({
    id: "godspeed-rune",
    name: "신속의 문장",
    aliases: ["Godspeed Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/godspeed-rune.png",
  }),
  buildRuneReference({
    id: "gozz-rune",
    name: "고즈의 문장",
    aliases: ["Gozz Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-tactics"],
    imageSrc: "/suikoden/runes/gozz-rune.png",
  }),
  buildRuneReference({
    id: "great-firefly-rune",
    name: "큰반딧불의 문장",
    aliases: ["Great Firefly Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "hawk-rune",
    name: "매의 문장",
    aliases: ["Hawk Rune"],
    category: "generalRune",
    games: ["suikoden-tactics"],
    imageSrc: "/suikoden/runes/hawk-rune.png",
  }),
  buildRuneReference({
    id: "haziness-rune",
    name: "양지의 문장",
    aliases: ["Haziness Rune"],
    category: "generalRune",
    games: ["suikoden-i","suikoden-ii","suikoden-iii"],
    imageSrc: "/suikoden/runes/haziness-rune.png",
  }),
  buildRuneReference({
    id: "hunter-rune",
    name: "사냥꾼의 문장",
    aliases: ["Hunter Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "isshin-rune",
    name: "일심의 문장",
    aliases: ["Isshin Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "jongleur-rune",
    name: "곡예사의 문장",
    aliases: ["Jongleur Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
    imageSrc: "/suikoden/runes/jongleur-rune.png",
  }),
  buildRuneReference({
    id: "kangacorn-rune",
    name: "캥거콘의 문장",
    aliases: ["Kangacorn Rune"],
    category: "generalRune",
    games: ["suikoden-tactics"],
  }),
  buildRuneReference({
    id: "kindness-rune",
    name: "상냥함의 문장",
    aliases: ["Kindness Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "kite-rune",
    name: "솔개의 문장",
    aliases: ["Kite Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-v"],
    imageSrc: "/suikoden/runes/kite-rune.png",
  }),
  buildRuneReference({
    id: "lion-rune",
    name: "사자의 문장",
    aliases: ["Lion Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/lion-rune.png",
  }),
  buildRuneReference({
    id: "lion-s-trial-rune",
    name: "Lion's Trial Rune",
    aliases: ["Lion's Trial Rune"],
    category: "generalRune",
    games: ["suikoden-i"],
  }),
  buildRuneReference({
    id: "magic-absorb-rune",
    name: "마력 흡수의 문장",
    aliases: ["Magic Absorb Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "magic-drain-rune",
    name: "마력 배출의 문장",
    aliases: ["Magic Drain Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "magical-rune",
    name: "마법의 문장",
    aliases: ["Magical Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "mallet-rune",
    name: "망치의 문장",
    aliases: ["Mallet Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "minotaur-rune",
    name: "미노타우로스의 문장",
    aliases: ["Minotaur Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "mischief-rune",
    name: "장난의 문장",
    aliases: ["Mischief Rune"],
    category: "generalRune",
    games: ["suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "mother-earth-sword-rune",
    name: "모대지검의 문장",
    aliases: ["Mother Earth Sword Rune"],
    category: "generalRune",
    games: ["suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "multi-strike-rune",
    name: "연속타격의 문장",
    aliases: ["Multi-Strike Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "night-rune",
    name: "밤의 문장",
    aliases: ["Night Rune"],
    category: "trueRune",
    games: ["suikoden-i","suikoden-ii","suikoden-iii"],
    imageSrc: "/suikoden/runes/night-rune.jpg",
  }),
  buildRuneReference({
    id: "nymph-rune",
    name: "님프의 문장",
    aliases: ["Nymph Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "ogre-rune",
    name: "오거의 문장",
    aliases: ["Ogre Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "pale-gate-rune",
    name: "창백한 문의 문장",
    aliases: ["Pale Gate Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-v"],
    imageSrc: "/suikoden/runes/pale-gate-rune.png",
  }),
  buildRuneReference({
    id: "parent-turtle-rune",
    name: "어미거북의 문장",
    aliases: ["Parent Turtle Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "phoenix-rune",
    name: "불사조의 문장",
    aliases: ["Phoenix Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "pixie-rune",
    name: "픽시의 문장",
    aliases: ["Pixie Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-v"],
    imageSrc: "/suikoden/runes/pixie-rune.png",
  }),
  buildRuneReference({
    id: "poison-rune",
    name: "독의 문장",
    aliases: ["Poison Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-v"],
  }),
  buildRuneReference({
    id: "power-rune",
    name: "힘의 문장",
    aliases: ["Power Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "prosperity-rune",
    name: "번영의 문장",
    aliases: ["Prosperity Rune"],
    category: "generalRune",
    games: ["suikoden-i","suikoden-ii","suikoden-iv","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/prosperity-rune.png",
  }),
  buildRuneReference({
    id: "raven-rune",
    name: "까마귀의 문장",
    aliases: ["Raven Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "red-rose-rune",
    name: "붉은 장미의 문장",
    aliases: ["Red Rose Rune"],
    category: "generalRune",
    games: ["suikoden-iii","suikoden-iv","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/red-rose-rune.png",
  }),
  buildRuneReference({
    id: "ripple-rune",
    name: "파문의 문장",
    aliases: ["Ripple Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "shield-rune",
    name: "방패의 문장",
    aliases: ["Shield Rune"],
    category: "generalRune",
    games: ["suikoden-iii","suikoden-v"],
    imageSrc: "/suikoden/runes/shield-rune.png",
  }),
  buildRuneReference({
    id: "shining-wing-rune",
    name: "빛나는 날개의 문장",
    aliases: ["Shining Wing Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "sickle-rune",
    name: "낫의 문장",
    aliases: ["Sickle Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/sickle-rune.gif",
  }),
  buildRuneReference({
    id: "sickle-weasle-rune",
    name: "족제비낫의 문장",
    aliases: ["Sickle-Weasle Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "silence-rune",
    name: "침묵의 문장",
    aliases: ["Silence Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "skunk-rune",
    name: "스컹크의 문장",
    aliases: ["Skunk Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-iv","suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "slash-rune",
    name: "참격의 문장",
    aliases: ["Slash Rune"],
    category: "generalRune",
    games: ["suikoden-iv"],
  }),
  buildRuneReference({
    id: "sleep-rune",
    name: "수면의 문장",
    aliases: ["Sleep Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-v"],
    imageSrc: "/suikoden/runes/sleep-rune.png",
  }),
  buildRuneReference({
    id: "solitude-rune",
    name: "고독의 문장",
    aliases: ["Solitude Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "sound-rune",
    name: "소리의 문장",
    aliases: ["Sound Rune"],
    category: "generalRune",
    games: ["suikoden-i","suikoden-ii"],
  }),
  buildRuneReference({
    id: "spreading-flame-rune",
    name: "번지는 불꽃의 문장",
    aliases: ["Spreading Flame Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "star-rune",
    name: "별의 문장",
    aliases: ["Star Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/star-rune.png",
  }),
  buildRuneReference({
    id: "steel-rune",
    name: "강철의 문장",
    aliases: ["Steel Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "strike-back-rune",
    name: "되받아치기의 문장",
    aliases: ["Strike-Back Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "sun-rune",
    name: "태양의 문장",
    aliases: ["Sun Rune"],
    category: "trueRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/sun-rune.png",
  }),
  buildRuneReference({
    id: "sunbeam-rune",
    name: "Sunbeam Rune",
    aliases: ["Sunbeam Rune"],
    category: "generalRune",
    games: ["suikoden-i","suikoden-ii","suikoden-iii","suikoden-iv","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/sunbeam-rune.png",
  }),
  buildRuneReference({
    id: "sword-of-cyclone-rune",
    name: "선풍검의 문장",
    aliases: ["Sword of Cyclone Rune"],
    category: "generalRune",
    games: ["suikoden-iii","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/sword-of-cyclone-rune.png",
  }),
  buildRuneReference({
    id: "sword-of-rage-rune",
    name: "분노검의 문장",
    aliases: ["Sword of Rage Rune"],
    category: "generalRune",
    games: ["suikoden-iii","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/sword-of-rage-rune.png",
  }),
  buildRuneReference({
    id: "sword-of-thunder-rune",
    name: "천둥검의 문장",
    aliases: ["Sword of Thunder Rune"],
    category: "generalRune",
    games: ["suikoden-iii","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/sword-of-thunder-rune.png",
  }),
  buildRuneReference({
    id: "sylph-rune",
    name: "실프의 문장",
    aliases: ["Sylph Rune"],
    category: "generalRune",
    games: ["suikoden-ii"],
  }),
  buildRuneReference({
    id: "titan-rune",
    name: "타이탄의 문장",
    aliases: ["Titan Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/titan-rune.png",
  }),
  buildRuneReference({
    id: "true-earth-rune",
    name: "진대지의 문장",
    aliases: ["True Earth Rune"],
    category: "trueRune",
    games: ["suikoden-iii"],
    imageSrc: "/suikoden/runes/true-earth-rune.png",
  }),
  buildRuneReference({
    id: "true-fire-rune",
    name: "진불의 문장",
    aliases: ["True Fire Rune"],
    category: "trueRune",
    games: ["suikoden-iii"],
    imageSrc: "/suikoden/runes/true-fire-rune.png",
  }),
  buildRuneReference({
    id: "true-lightning-rune",
    name: "진번개의 문장",
    aliases: ["True Lightning Rune"],
    category: "trueRune",
    games: ["suikoden-iii"],
    imageSrc: "/suikoden/runes/true-lightning-rune.png",
  }),
  buildRuneReference({
    id: "true-water-rune",
    name: "진물의 문장",
    aliases: ["True Water Rune"],
    category: "trueRune",
    games: ["suikoden-iii"],
    imageSrc: "/suikoden/runes/true-water-rune.png",
  }),
  buildRuneReference({
    id: "true-wind-rune",
    name: "진바람의 문장",
    aliases: ["True Wind Rune"],
    category: "trueRune",
    games: ["suikoden-i","suikoden-ii","suikoden-iii"],
    imageSrc: "/suikoden/runes/true-wind-rune.png",
  }),
  buildRuneReference({
    id: "twilight-rune",
    name: "Twilight Rune",
    aliases: ["Twilight Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
    imageSrc: "/suikoden/runes/twilight-rune.png",
  }),
  buildRuneReference({
    id: "venom-rune",
    name: "맹독의 문장",
    aliases: ["Venom Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "violence-rune",
    name: "폭력의 문장",
    aliases: ["Violence Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-iv","suikoden-tactics","suikoden-v"],
  }),
  buildRuneReference({
    id: "viper-rune",
    name: "독사의 문장",
    aliases: ["Viper Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-tactics","suikoden-v"],
    imageSrc: "/suikoden/runes/viper-rune.png",
  }),
  buildRuneReference({
    id: "wall-rune",
    name: "벽의 문장",
    aliases: ["Wall Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-v"],
    imageSrc: "/suikoden/runes/wall-rune.png",
  }),
  buildRuneReference({
    id: "war-horse-rune",
    name: "군마의 문장",
    aliases: ["War Horse Rune"],
    category: "generalRune",
    games: ["suikoden-iii"],
  }),
  buildRuneReference({
    id: "water-sealing-rune",
    name: "물 봉인의 문장",
    aliases: ["Water Sealing Rune"],
    category: "generalRune",
    games: ["suikoden-v"],
  }),
  buildRuneReference({
    id: "window-rune",
    name: "창문의 문장",
    aliases: ["Window Rune"],
    category: "generalRune",
    games: ["suikoden-i"],
  }),
  buildRuneReference({
    id: "wizard-rune",
    name: "마법사의 문장",
    aliases: ["Wizard Rune"],
    category: "generalRune",
    games: ["suikoden-ii","suikoden-iii","suikoden-iv","suikoden-tactics"],
    imageSrc: "/suikoden/runes/wizard-rune.png",
  }),
  buildRuneReference({
    id: "wrath-rune",
    name: "격노의 문장",
    aliases: ["Wrath Rune"],
    category: "generalRune",
    games: ["suikoden-iii","suikoden-v"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-01",
    name: "미공개 진정한 문장 1",
    aliases: ["Unknown True Rune 1"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-02",
    name: "미공개 진정한 문장 2",
    aliases: ["Unknown True Rune 2"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-03",
    name: "미공개 진정한 문장 3",
    aliases: ["Unknown True Rune 3"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-04",
    name: "미공개 진정한 문장 4",
    aliases: ["Unknown True Rune 4"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-05",
    name: "미공개 진정한 문장 5",
    aliases: ["Unknown True Rune 5"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-06",
    name: "미공개 진정한 문장 6",
    aliases: ["Unknown True Rune 6"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-07",
    name: "미공개 진정한 문장 7",
    aliases: ["Unknown True Rune 7"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-08",
    name: "미공개 진정한 문장 8",
    aliases: ["Unknown True Rune 8"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
  buildRuneReference({
    id: "unknown-true-rune-09",
    name: "미공개 진정한 문장 9",
    aliases: ["Unknown True Rune 9"],
    category: "trueRune",
    games: ["unrevealed"],
  }),
] as const;

const RUNE_REFERENCE_BY_NAME = new Map<string, RuneReference>();

RUNE_REFERENCES.forEach((rune) => {
  [rune.name, ...rune.aliases].forEach((name) => {
    RUNE_REFERENCE_BY_NAME.set(name.toLowerCase(), rune);
  });
});

export const resolveRuneReference = (name: string) => {
  return RUNE_REFERENCE_BY_NAME.get(name.toLowerCase());
};

export const getRuneReference = (runeId: string) => {
  return RUNE_REFERENCES.find((rune) => rune.id === runeId) ?? null;
};

export const getRuneIndexPage = (pageId: RuneIndexPageId) => {
  return RUNE_INDEX_PAGES.find((page) => page.id === pageId) ??
    RUNE_INDEX_PAGES[0];
};

export const getRuneIndexPageByCategory = (category: RuneCategoryId) => {
  return RUNE_INDEX_PAGES.find((page) =>
    (page.categories as readonly RuneCategoryId[]).includes(category),
  ) ?? RUNE_INDEX_PAGES[0];
};

export const getRuneReferencesByPageId = (pageId: RuneIndexPageId) => {
  const page = getRuneIndexPage(pageId);

  return RUNE_REFERENCES.filter((rune) =>
    (page.categories as readonly RuneCategoryId[]).includes(rune.category),
  ).toSorted((left, right) =>
    left.name.localeCompare(right.name, "ko-KR", { numeric: true }),
  );
};

export const formatRuneGames = (games: readonly string[]) =>
  games
    .map((game) =>
      RUNE_GAME_LABELS[game as keyof typeof RUNE_GAME_LABELS] ?? game,
    )
    .join(" / ");
