/**
 * Game8의 환상수호전 I 몬스터 표에서 가져온 원자료 행을 보관합니다.
 */

export type Game8MonsterSourceRecord = {
  monster: string;
  entries: readonly string[];
};

export const GAME8_SUIKODEN_I_MONSTER_SOURCE_RECORDS = [
  { monster: `Crow`, entries: [`Around Gregminster (Chapter 1) | Bandana (High)`] },
  { monster: `Mosquito`, entries: [`Around Gregminster (Chapter 1) | Medicine (High), Holy Rune (Medium)`] },
  { monster: `Furball`, entries: [`Around Gregminster (Chapter 1) | Defective Urn (High), Celadon Urn (Low), Octopus Pot (Medium)`] },
  { monster: `Red Soldier Ant`, entries: [`Around Gregminster (Chapter 1) | No Drop`] },
  { monster: `Wild Boar`, entries: [`Around Gregminster (Chapter 1) | Earth Rune Piece (High)`] },
  { monster: `Holly Boy`, entries: [`Magician's Island | Robe (Medium), Medicine (High)`, `Great Forest | Flower Painting (Medium), Lovers' Garden (Low), Graffiti (High)`] },
  { monster: `FurFur`, entries: [`Magician's Island | Wooden Shoes (Medium), Medicine (High)`] },
  { monster: `Clay Doll`, entries: [`Magician's Island | Medicine (High)`, `Cave of the Past | Full Armor (Medium), Mega Medicine (High)`] },
  { monster: `Bandit (Sword) (1)`, entries: [`Mt. Seifu | No Drop`] },
  { monster: `Bandit (Sword) (2)`, entries: [`Mt. Seifu | Shoulder Pads (High)`] },
  { monster: `Bandit (Bow)`, entries: [`Mt. Seifu | Tunic (Medium), Medicine (High)`] },
  { monster: `Black Wild Boar`, entries: [`Mt. Seifu | No Drop`] },
  { monster: `Soldier Ant`, entries: [`Mt. Seifu | Pointy Hat (High)`] },
  { monster: `Queen Ant`, entries: [`Mt. Seifu | Pointy Hat (High)`, `Seek Valley | Silver Hat (High)`] },
  { monster: `Varkas`, entries: [`Mt. Seifu | No Drop`] },
  { monster: `Sydonia`, entries: [`Mt. Seifu | No Drop`] },
  { monster: `Empire Soldier (Sword)`, entries: [`Rockland Military Government Office | No Drop`, `Lenankamp | No Drop`, `Seika | No Drop`, `Kouan Military Government Office | Chest Plate (High)`] },
  { monster: `Empire Soldier (Spear)`, entries: [`Rockland Military Government Office | No Drop`, `Lenankamp | No Drop`, `Seika | Flower Vase (Medium), Defective Urn (High)`] },
  { monster: `Empire Soldier (Bow)`, entries: [`Rockland Military Government Office | No Drop`, `Lenankamp | No Drop`] },
  { monster: `Empire Soldier (Female)`, entries: [`Rockland Military Government Office | Headband (High)`] },
  { monster: `Empire Captain (Male)`, entries: [`Rockland Military Government Office | No Drop`] },
  { monster: `Killer Slime`, entries: [`Mt. Tigerwolf | Water Rune Piece (High)`] },
  { monster: `Slasher Rabbit`, entries: [`Mt. Tigerwolf | Martial Arts Robe (High)`] },
  { monster: `Giant Snail`, entries: [`Mt. Tigerwolf | Defense Rune Piece (High)`] },
  { monster: `Killer Rabbit`, entries: [`Around Seika and Kaku | Peeing Boy (Low), Hex Doll (High), Japanese Dish (Medium)`] },
  { monster: `Flying Squirrel`, entries: [`Around Seika and Kaku | Holy Rune (High)`] },
  { monster: `Beast Commander`, entries: [`Around Seika and Kaku | Blue Ribbon (High), Phero Rune (Medium)`] },
  { monster: `Roc`, entries: [`Around Seika and Kaku | Feather (High)`] },
  { monster: `Giant Slug`, entries: [`Toran Lake Castle | Medicine (High)`] },
  { monster: `Oannes`, entries: [`Toran Lake Castle | Antitoxin (High)`] },
  { monster: `Ghost Armor`, entries: [`Toran Lake Castle | Chest Plate (High)`] },
  { monster: `Zombie Dragon`, entries: [`Toran Lake Castle | Lightning Rune (High)`] },
  { monster: `Robot Soldier (Sword)`, entries: [`Lepant's Mansion | Defective Urn (High), Persian Lamp (Low), Flower Vase (Medium)`] },
  { monster: `Robot Soldier (Spear)`, entries: [`Lepant's Mansion | Pointy Hat (High)`] },
  { monster: `Slot Man`, entries: [`Lepant's Mansion | Flower Vase (Medium), Defective Urn (High), Persian Lamp (Low)`] },
  { monster: `Assassin`, entries: [`Headquarters | No Drop`] },
  { monster: `Holly Spirit`, entries: [`Great Forest | Toe Shoes (Medium), Needle (High)`] },
  { monster: `Kobold (Sword)`, entries: [`Great Forest | Wooden Shield (High)`, `Around the Village of the Elves | Wooden Shield (High)`] },
  { monster: `Kobold (Bow)`, entries: [`Great Forest | Collar (High), Medicine (Medium)`, `Around the Village of the Elves | Collar (High), Medicine (Medium)`] },
  { monster: `Kobold (Mage)`, entries: [`Around the Village of the Elves | Guard Robe (High), Fire Rune (Medium)`] },
  { monster: `Strong Arm`, entries: [`Around the Village of the Elves | Silver Ring (High)`] },
  { monster: `Eagle Man`, entries: [`Dwarf Trail | Flower Painting (Medium), Lovers' Garden (Low), Graffiti (High)`] },
  { monster: `Death Boar`, entries: [`Dwarf Trail | Boar Rune (Medium), Fur Cape (High)`] },
  { monster: `Dwarf`, entries: [`Dwarf Trail | Martial Arts Robe (High)`] },
  { monster: `Crimson Dwarf`, entries: [`Dwarves' Vault | Medicine (High), Escape Talisman (Medium)`] },
  { monster: `Death Machine (Sword)`, entries: [`Dwarves' Vault | Iron Shield (High)`] },
  { monster: `Death Machine (Spear)`, entries: [`Dwarves' Vault | Half Helmet (High), Gadget Rune (Medium)`] },
  { monster: `Gigantes`, entries: [`Dwarves' Vault | Goldlet (High)`] },
  { monster: `Veteran Soldier (Bow)`, entries: [`Pannu Yakuta Castle | Emblem (High)`] },
  { monster: `Veteran Soldier (Spear)`, entries: [`Pannu Yakuta Castle | Leather Armor (High)`] },
  { monster: `Veteran Soldier (Female)`, entries: [`Pannu Yakuta Castle | No Drop`] },
  { monster: `Devil Armor`, entries: [`Pannu Yakuta Castle | Main-Gauche (High)`] },
  { monster: `Devil Shield`, entries: [`Pannu Yakuta Castle | Chaos Shield (High)`] },
  { monster: `Dragon`, entries: [`Pannu Yakuta Castle | Half Armor (High)`] },
  { monster: `Holly Master`, entries: [`Around Teien and Rikon | Magic Robe (Low), Needle (Medium), Nameless Urn (High)`] },
  { monster: `Mad Ivy`, entries: [`Around Teien and Rikon | Headgear (High)`, `Scarleticia Castle | Headgear (High)`] },
  { monster: `Creeper`, entries: [`Around Teien and Rikon | Earth Rune (High)`, `Scarleticia Castle | Earth Rune (High)`] },
  { monster: `Red Slime`, entries: [`Soniere Prison | Chinese Dish (Medium), Hex Doll (High), Bonsai Tree (Low)`] },
  { monster: `Viperman`, entries: [`Soniere Prison | Ninja Garb (High)`] },
  { monster: `Delf`, entries: [`Soniere Prison | No Drop`] },
  { monster: `Nightmare`, entries: [`Soniere Prison | Opal (High)`, `Scarleticia Castle | Opal (High)`] },
  { monster: `Dagon`, entries: [`Around Kirov | Dragon Armor (High), Water Rune (Medium)`] },
  { monster: `Pseudo-Siren`, entries: [`Around Kirov | Prosperity Rune (High)`] },
  { monster: `Grizzly Bear`, entries: [`Around Kirov | Headgear (High)`] },
  { monster: `Hawk Man`, entries: [`Kalekka | Wide Urn (Medium), Black Urn (Low), Defective Urn (High)`] },
  { monster: `Shadow`, entries: [`Kalekka | Silverlet (High), Rose Brooch (Medium)`] },
  { monster: `Demon Hound`, entries: [`Kalekka | Silver Collar (High)`] },
  { monster: `Angie`, entries: [`Pirate's Fortress | No Drop`] },
  { monster: `Kanak`, entries: [`Pirate's Fortress | No Drop`] },
  { monster: `Leonardo`, entries: [`Pirate's Fortress | No Drop`] },
  { monster: `Whip Wolf`, entries: [`Around Warriors' Village | Resurrection Rune (High)`] },
  { monster: `Hell Hound`, entries: [`Around Warriors' Village | No Drop`, `Moravia | No Drop`] },
  { monster: `Grave Master`, entries: [`Around Warriors' Village | Full Helmet (High), Guard Ring (Medium)`] },
  { monster: `Sorcerer`, entries: [`Around Warriors' Village | Master's Robe (High)`] },
  { monster: `Neclord`, entries: [`Neclord's Castle | No Drop`] },
  { monster: `Banshee`, entries: [`Cave of the Past | Landscape Scroll (Low), Escape Talisman (High), Graffiti (Medium)`] },
  { monster: `Red Elemental`, entries: [`Cave of the Past | Speed Rune Piece (High)`] },
  { monster: `Larvae`, entries: [`Neclord's Castle | Fine China (Low), Defective Urn (High), Blue Dragon Urn (Medium)`] },
  { monster: `Demon Sorcerer`, entries: [`Neclord's Castle | Mega Medicine (High), Wind Rune (Medium)`] },
  { monster: `Hell Unicorn`, entries: [`Neclord's Castle | Star Earrings (High)`] },
  { monster: `Black Elemental`, entries: [`Dragon's Den | Magic Rune Piece (High)`] },
  { monster: `Magic Shield`, entries: [`Dragon's Den | Earth Shield (High)`] },
  { monster: `Sunshine King`, entries: [`Dragon's Den | Cyclone Rune (Medium), Window Set 3 (High)`] },
  { monster: `Ivy`, entries: [`Around the Dragon Knights' Fortress | Knight Statue (Low), Peeing Boy (Medium), Hex Doll (High)`, `Seek Valley | Knight Statue (Low), Peeing Boy (Medium), Hex Doll (High)`] },
  { monster: `Shadow Man`, entries: [`Around the Dragon Knights' Fortress | No Drop`] },
  { monster: `Mirage`, entries: [`Around the Dragon Knights' Fortress | Speed Ring (High)`, `Around Moravia | Speed Ring (High)`] },
  { monster: `Rock Buster`, entries: [`Seek Valley | Tai Chi Garb (Medium), Mega Medicine (High)`] },
  { monster: `Wyvern`, entries: [`Seek Valley | Power Gloves (High)`] },
  { monster: `Crystal Core`, entries: [`Seek Valley | No Drop`] },
  { monster: `Rabbit Bird`, entries: [`Around Moravia | Sacrificial Buddha (High)`] },
  { monster: `Earth Golem`, entries: [`Around Moravia | Master's Garb (High)`] },
  { monster: `Elite Soldier`, entries: [`Moravia | Rage Rune (High)`, `Floating Fortress of Shasarazade | Horned Helmet (Medium), Mega Medicine (High)`] },
  { monster: `Whip Master`, entries: [`Moravia | Hex Doll (High), Bonsai Tree (Medium), Goddess Statue (Low)`] },
  { monster: `Ninja`, entries: [`Moravia | Cape of Darkness (High), Winged Boots (Medium)`] },
  { monster: `Magus`, entries: [`Moravia | Fortune Rune (High)`] },
  { monster: `Siren`, entries: [`Floating Fortress of Shasarazade | Sound Set 3 (High), Flowing Rune (Medium)`] },
  { monster: `Kerberos`, entries: [`Floating Fortress of Shasarazade | Gold Collar (High)`] },
  { monster: `Shell Venus`, entries: [`Floating Fortress of Shasarazade | No Drop`] },
  { monster: `Sonya Shulen`, entries: [`Floating Fortress of Shasarazade | No Drop`] },
  { monster: `Ninja Master`, entries: [`Around Gregminster (Chapter 8) | Crimson Cape (High)`] },
  { monster: `Simurgh`, entries: [`Around Gregminster (Chapter 8) | Thunder Rune (High)`] },
  { monster: `Orc`, entries: [`Around Gregminster (Chapter 8) | Beauties of Nature (Low), Lovers' Garden (Medium), Graffiti (High)`] },
  { monster: `Ain Gide`, entries: [`Gregminster | No Drop`] },
  { monster: `Imperial Guard (Male)`, entries: [`Gregminster Castle | Mega Medicine (High)`] },
  { monster: `Imperial Guard (Female)`, entries: [`Gregminster Castle | No Drop`] },
  { monster: `Phantom`, entries: [`Gregminster Castle | Earth Boots (High)`] },
  { monster: `Colossus`, entries: [`Gregminster Castle | Power Ring (High), Mother Earth Rune (Medium)`] },
  { monster: `Ekidonna`, entries: [`Gregminster Castle | Windspun Armor (High)`] },
  { monster: `Golden Hydra (Right)`, entries: [`Gregminster Castle | No Drop`] },
  { monster: `Golden Hydra (Middle)`, entries: [`Gregminster Castle | No Drop`] },
  { monster: `Golden Hydra (Left)`, entries: [`Gregminster Castle | No Drop`] },
] as const satisfies readonly Game8MonsterSourceRecord[];

export const GAME8_SUIKODEN_II_MONSTER_SOURCE_RECORDS = [
  { monster: `Highlands (Sword)`, entries: [`Tenzan Pass | Medicine (High), Greaves (Medium)`, `Kyaro Town | Medicine (High)`, `Mercenary Fortress | Defective Urn (Medium), Celadon Urn (Rare), Octopus Pot (Low)`, `Highland Garrison | Shoulder Pads (Medium)`, `Greenhill City | Headgear (Medium), Fire Wall Scroll (Low)`, `Muse City | Wooden Shield (Medium), Lunch Box (Low)`, `Muse City | Half Helmet (Medium)`, `Muse City | Iron Shield (Low)`, `Greenhill Forest | Medicine (Medium)`, `Rockaxe Castle | Hex Doll (Medium), Knight Statue (Rare), Recipe 36 (Low)`, `L'Renouille | No Drop`] },
  { monster: `Highlands (Spear)`, entries: [`Tenzan Pass | Medicine (High), Leather Hat (Medium), Cape (Low)`, `Kyaro Town | Hazy Rune (High)`, `Mercenary Fortress | Chest Plate (Low)`, `Highland Garrison | Silence Rune (Medium)`, `Muse City | Medicine (Medium)`, `Two River City | Chain Mail (Medium)`, `Greenhill City | Medicine (Medium), Scale Mail (Low)`, `Muse City | Scale Mail (Medium)`, `Muse City | Full Plate (Low)`, `Greenhill Forest | Iron Boots (Low)`, `Rockaxe Castle | Escape Talisman (Medium)`, `L'Renouille | No Drop`] },
  { monster: `Commander`, entries: [`Tenzan Pass | Mega Medicine (High)`, `Mercenary Fortress | Mega Medicine (Low)`, `Muse City | Circlet (Low)`, `Two River City | Mega Medicine (High)`, `Muse City | Mega Medicine (Medium)`, `Greenhill Forest | Full Helmet (Low)`, `Rockaxe Castle | Chaos Shield (Low)`, `L'Renouille | Flame Helmet (Low), Mega Medicine (Medium)`] },
  { monster: `Holly Boy`, entries: [`Area A | Medicine (High), Spinach Juice (Low)`, `Area F1 | Needle (Medium), Spinach Juice (Low)`, `Greenhill City | Medicine (Medium), Spinach Juice (Low)`, `Greenhill Forest | Drinking Set (Rare), Spinach Juice (Low)`, `Greenhill Forest | Toy Boat (Rare), Spinach Juice (Low)`] },
  { monster: `FurFur`, entries: [`Area A | Clay Guardian Scroll (Medium)`] },
  { monster: `Slasher Rabbit`, entries: [`Area A | Technique Rune (Low), Cream Stew (Rare)`, `North Sparrow Pass | Double-beat Rune (Low), Cream Stew (Rare)`, `Area B | Technique Rune (Low), Antitoxin (High)`] },
  { monster: `Wolf`, entries: [`North Sparrow Pass | No Drop`] },
  { monster: `Bandit A`, entries: [`North Sparrow Pass | Escape Talisman (High), Cheek Guards (Medium)`] },
  { monster: `Bandit B`, entries: [`North Sparrow Pass | Medicine (High), Rising Sun Bento (Low)`] },
  { monster: `Bandit C`, entries: [`North Sparrow Pass | Hex Doll (Medium), Japanese Dish (Low), Peeing Boy (Rare)`] },
  { monster: `KillerBee`, entries: [`North Sparrow Pass | Flaming Arrows Scroll (Low)`] },
  { monster: `BonBon`, entries: [`North Sparrow Pass | Defective Urn (Medium), Celadon Urn (Rare), Octopus Pot (Low)`, `Area B | Defective Urn (Medium), Celadon Urn (Rare), Octopus Pot (Low)`, `Area A | Defective Urn (Medium), Celadon Urn (Rare), Octopus Pot (Low)`] },
  { monster: `Spider`, entries: [`Area B | Leather Cape (Medium)`, `Ryube Forest | Leather Cape (Medium)`] },
  { monster: `Highlands (Bow)`, entries: [`Kyaro Town | No Drop`, `Mercenary Fortress | Medicine (High)`, `Highland Garrison | Medicine (Medium)`, `Muse City | Great Hawk Rune (Medium)`, `Two River City | Medicine (Medium)`, `Greenhill City | Fur Cape (Medium)`, `Muse City | Mega Medicine (Medium)`, `Muse City | No Drop`, `Greenhill Forest | No Drop`, `Rockaxe Castle | Recipe 36 (Medium), Gengis Khan (Low)`, `L'Renouille | No Drop`] },
  { monster: `Rowd`, entries: [`Kyaro Town | No Drop`] },
  { monster: `Woodpecker`, entries: [`Area A | Wind of Sleep Scroll (Low), Fried Chicken (Rare)`, `Ryube Forest | Killer Rune (Low), Sweet & Sour Fish (Rare)`] },
  { monster: `ShadowDog`, entries: [`Area A | Hazy Rune (Low)`] },
  { monster: `Wild Boar`, entries: [`Ryube Forest | Pointy Hat (Low), Cream Cutlets (Rare)`] },
  { monster: `Giant Snail`, entries: [`Ryube Forest | Antitoxin (High)`] },
  { monster: `Sickle`, entries: [`Area C1 | Antitoxin (High), Gale Rune (Medium)`] },
  { monster: `GoldBoar`, entries: [`Area C1 | Revenge Earth Scroll (Low)`] },
  { monster: `KillSpider`, entries: [`Area C1 | Cheek Guards (Medium)`] },
  { monster: `Mr.Venus`, entries: [`Sindar Ruins | Unicorn Rune (Medium), Titan Rune (Medium)`] },
  { monster: `Magician`, entries: [`Sindar Ruins | Escape Talisman (High), Guard Robe (Low)`] },
  { monster: `MegaWatt`, entries: [`Sindar Ruins | Leather Armor (Medium), Green Salad (Low)`] },
  { monster: `Creeper`, entries: [`Sindar Ruins | Medicine (High), Throat Drop (Medium)`] },
  { monster: `Armadillon`, entries: [`Highland Garrison | Chest Plate (Medium)`] },
  { monster: `Armadilloid`, entries: [`Highland Garrison | Defective Urn (Medium), Flower Vase (Medium), Blue Dragon Urn (Low)`] },
  { monster: `Killer Rabbit`, entries: [`Highland Garrison | Belt of Strength (Low)`] },
  { monster: `Flying Squirrel`, entries: [`Area D | Medicine (Medium), Medicine Rune (Rare), Celadon Urn (Rare)`] },
  { monster: `Nariqua`, entries: [`Area D | Pixie Rune (Rare), Dryad Rune (Rare), Nymph Rune (Rare)`] },
  { monster: `DarkBunny`, entries: [`Area D | Shoulder Pads (Medium)`] },
  { monster: `Zombie (A)`, entries: [`North Window | No Drop`, `North Window | Defective Urn (Low)`, `Tinto Pass | Defective Urn (Low)`, `Tinto Mines | Defective Urn (Low), Escape Talisman (Medium)`, `Tigermouth Village | Defective Urn (Low)`, `Crom Village | Defective Urn (Low)`, `Tinto Mines | Defective Urn (Low), Power Gloves (Rare)`, `Tinto City | Defective Urn (Low)`] },
  { monster: `Zombie (B)`, entries: [`North Window | Hex Doll (Low)`, `North Window | Hex Doll (Low), Half Helmet (Rare)`, `Tinto Pass | Hex Doll (Low), Silver Collar (Rare)`, `Tinto Mines | Hex Doll (Low)`, `Tigermouth Village | Hex Doll (Low)`, `Crom Village | Hex Doll (Low)`, `Tinto Mines | Hex Doll (Low)`, `Tinto City | Hex Doll (Low)`] },
  { monster: `Griffin`, entries: [`Cave of the Wind | Wind Rune (Low), Wind Hat (Rare)`, `Forest Village | Shredding Wind Scroll (Low)`] },
  { monster: `Minos`, entries: [`Cave of the Wind | Mega Medicine (Low), Gozz Rune (Rare), Grilled Beef (Rare)`] },
  { monster: `SunKing`, entries: [`Cave of the Wind | Wall Rune (Low)`] },
  { monster: `Sorcerer`, entries: [`Cave of the Wind | Escape Talisman (Medium)`, `North Window | Fish Badge (Low)`] },
  { monster: `Star Dragon Sword`, entries: [`Cave of the Wind | No Drop`] },
  { monster: `Shadow Man`, entries: [`North Window | Antitoxin (High)`] },
  { monster: `Spikebeak`, entries: [`Area E | Mega Medicine (Medium), Balance Rune (Low)`] },
  { monster: `Rockadillo`, entries: [`Area E | Turtle Plans 1 (Medium)`] },
  { monster: `Sandillo`, entries: [`Area E | Japanese Dish (Medium), Chinese Dish (Medium), Peeing Boy (Low)`] },
  { monster: `Siren`, entries: [`Two River Sewers | Banshee Rune (Low), Water Amulet (Low)`] },
  { monster: `Shadow`, entries: [`Two River Sewers | Main-Gauche (Low), Throat Drop (Medium)`] },
  { monster: `DevilEye`, entries: [`Two River Sewers | Kite Rune (Low)`] },
  { monster: `LandShark`, entries: [`Two River Sewers | Recipe 21 (Medium), Guard Ring (Low), Dried Fish (Low)`] },
  { monster: `Eagle Man`, entries: [`Kobold Village Forest | Recipe 12 (Medium), Double-Strike Rune (Low), Sandwich (Low)`] },
  { monster: `Mirage`, entries: [`Kobold Village Forest | Fire Emblem (Low)`] },
  { monster: `RaggedOne`, entries: [`Area F1 | Turtle Plans 2 (Medium), Chick (Special) (Low), Knight Statue (Rare)`] },
  { monster: `Sauroid`, entries: [`Area F1 | Protection Mist Scroll (Low), Sweet & Sour Fish (Low)`] },
  { monster: `Monwer`, entries: [`Greenhill City | Needle (Medium)`] },
  { monster: `Melonzoo`, entries: [`Greenhill City | Viper Rune (Low)`] },
  { monster: `HollyElf`, entries: [`Greenhill City | Dryad Rune (Low), Toe Shoes (Medium)`] },
  { monster: `PapaHolly`, entries: [`Greenhill Forest | Heavy Collar (Low), Seed Potato (Once Only), Canopy Defense Scroll (Rare)`] },
  { monster: `DoReMi Elf (Red)`, entries: [`Path to Matilda | Sound Set 2 (Low)`, `Greenhill Forest | Throat Drop (Medium), Recipe 34 (Low), Japanese Stew (Low)`] },
  { monster: `DoReMi Elf (Blue)`, entries: [`Path to Matilda | Sound Set 2 (Low)`, `Greenhill Forest | Throat Drop (Medium), Recipe 34 (Low), Japanese Stew (Low)`] },
  { monster: `DoReMi Elf (Yellow)`, entries: [`Path to Matilda | Sound Set 2 (Low)`, `Greenhill Forest | Throat Drop (Medium), Recipe 34 (Low), Japanese Stew (Low)`] },
  { monster: `DoReMi Elf (Green)`, entries: [`Path to Matilda | Sound Set 2 (Low)`, `Greenhill Forest | Throat Drop (Medium), Recipe 34 (Low), Japanese Stew (Low)`] },
  { monster: `DoReMi Elf (Pink)`, entries: [`Path to Matilda | Sound Set 2 (Low)`, `Greenhill Forest | Throat Drop (Medium), Recipe 34 (Low), Japanese Stew (Low)`] },
  { monster: `DoReMi Elf (Aqua)`, entries: [`Path to Matilda | Sound Set 2 (Low)`, `Greenhill Forest | Throat Drop (Medium), Recipe 34 (Low), Japanese Stew (Low)`] },
  { monster: `ZombieSlug`, entries: [`Greenhill Forest | Recipe 29 (Medium), Lightning Amulet (Low)`] },
  { monster: `Phantom`, entries: [`Area G | Healing Wind Scroll (Low)`] },
  { monster: `PinkBird`, entries: [`Area G | Sylph Rune (Low), Skunk Rune (Low)`] },
  { monster: `TimeKnight`, entries: [`Area C2 | Mega Medicine (Low)`] },
  { monster: `WhiteTiger`, entries: [`Area C2 | Double-beat Rune (Low)`] },
  { monster: `Tiger`, entries: [`Banner Pass | Window Set 1 (Low)`] },
  { monster: `RanRan`, entries: [`Banner Pass | Medicine (Medium), Silverlet (Low)`] },
  { monster: `RinRin`, entries: [`Banner Pass | Barrier Rune (Low), Diet Lunch (Low)`] },
  { monster: `TenTen`, entries: [`Banner Pass | Ninja Garb (Low)`] },
  { monster: `Samurai`, entries: [`Banner Pass | Hex Doll (Medium), Chinese Dish (Low), Bonsai Tree (Rare)`] },
  { monster: `Air Lizard`, entries: [`Tinto Pass | Window Set 2 (Medium), Firefly Rune (Low)`] },
  { monster: `KillerDog`, entries: [`Tinto Pass | Chaos Shield (Low), Antitoxin (Medium)`] },
  { monster: `GhostSlug`, entries: [`Area H | Dancing Flames Scroll (Low)`] },
  { monster: `Skeleton (Sword)`, entries: [`Area H | Iron Shield (Medium)`, `Tinto Mines | Iron Shield (Medium)`] },
  { monster: `Skeleton (Spear)`, entries: [`Area H | Gauntlet (Medium)`, `Tinto Mines | Gauntlet (Medium)`] },
  { monster: `Sierra`, entries: [`Tigermouth Village | No Drop`] },
  { monster: `Hell Unicorn`, entries: [`Tinto Mines | Fire Sealing Rune (Low)`] },
  { monster: `Neclordia`, entries: [`Tinto Mines | Master's Garb (Low), Hex Doll (Low), Knight Statue (Rare)`] },
  { monster: `EyeFlower`, entries: [`Area F2 | Medicine (Medium), Spinach Seedling (Low)`] },
  { monster: `Kookaburra`, entries: [`Area F2 | Guard Ring (Low)`] },
  { monster: `TargetGirl`, entries: [`Greenhill Forest | Waking Rune (Low), Pixie Rune (Rare), Nymph Rune (Rare)`] },
  { monster: `GrandHolly`, entries: [`Greenhill Forest | Cape of Darkness (Medium)`] },
  { monster: `Holly Fairy`, entries: [`Greenhill Forest | Rain of Kindness Scroll (Low), Dryad Rune (Low)`] },
  { monster: `Karayans (A)`, entries: [`Greenhill Forest | No Drop`] },
  { monster: `Karayans (B)`, entries: [`Greenhill Forest | No Drop`] },
  { monster: `Karayans (C)`, entries: [`Greenhill Forest | No Drop`] },
  { monster: `IronMoon`, entries: [`Area C3 | Graffiti (Medium), Flower Painting (Low), Landscape Scroll (Rare)`] },
  { monster: `Copper Sun`, entries: [`Area C3 | Rage Rune (Low)`] },
  { monster: `Fisheye`, entries: [`Area C3 | Protection Mist Scroll (Low)`] },
  { monster: `Fei Yu`, entries: [`Area G | Gold Bar (Rare)`] },
  { monster: `Li Lan`, entries: [`Area G | Mega Medicine (Medium), Antitoxin (Medium)`] },
  { monster: `Shiu Lin`, entries: [`Area G | Flowing Rune (Rare)`] },
  { monster: `BlackTiger`, entries: [`Area G | No Drop`] },
  { monster: `Cockatrice`, entries: [`Rockaxe Castle | Thunder Rune (Rare)`] },
  { monster: `Hippogriff`, entries: [`Rockaxe Castle | Wind Amulet (Low)`] },
  { monster: `M-Knight`, entries: [`Rockaxe Castle | Master's Robe (Low), Knight Rune (Rare)`] },
  { monster: `HawkMan`, entries: [`Mt. Rakutei | Great Hawk Rune (Low)`] },
  { monster: `Spiker`, entries: [`Mt. Rakutei | Defective Urn (Medium), Wide Urn (Low), Black Urn (Rare)`] },
  { monster: `Assassin`, entries: [`Mt. Rakutei | Escape Talisman (Medium)`] },
  { monster: `Pixie`, entries: [`Mt. Rakutei | Antitoxin (Medium), Pixie Rune (Low)`, `Mt. Rakutei | Pixie Rune (Low)`] },
  { monster: `SkyKnight`, entries: [`Mt. Rakutei | Turtle Plans 3 (Once Only)`] },
  { monster: `Leathercut`, entries: [`Mt. Rakutei | Defective Urn (Medium), Blue Dragon Urn (Low), Fine China (Rare)`] },
  { monster: `IronClaw`, entries: [`Mt. Rakutei | Medicine (Medium)`] },
  { monster: `Minotaurus`, entries: [`Area I | Mother Earth Rune (Rare), Spicy Stew (Low)`, `Tenzan Pass | Graffiti (Medium), Lovers' Garden (Low), Nature's Beauty (Rare)`] },
  { monster: `Colossus`, entries: [`Area I | Full Helmet (Medium)`] },
  { monster: `Bronzem`, entries: [`L'Renouille | Master's Garb (Low)`] },
  { monster: `Magus`, entries: [`L'Renouille | Hex Doll (Medium), Peeing Boy (Low), Goddess Statue (Rare)`, `Tenzan Pass | Wind Amulet (Low)`] },
  { monster: `Chimera`, entries: [`L'Renouille | Blood Armor (Rare), Lucky Ring (Medium)`] },
  { monster: `Salamander`, entries: [`Sindar Ruins | Fire Lizard Rune (Low)`] },
] as const satisfies readonly Game8MonsterSourceRecord[];
