export const SUIKODEN_II_CHARACTER_COPY = {
  eyebrow: "Characters",
  title: "Suikoden II",
  body: "Dunan Unification War에 합류하는 108성 및 주요 인물을 이름, 별의 자리, 구분, 주요 등장 지역 순으로 정리합니다.",
  tableTitle: "108 Stars & Character Index",
  detailCta: "View Character Entry",
  backToList: "Back to Suikoden II Characters",
} as const;

export const SUIKODEN_II_CHARACTERS = [
  {
    "id": "hero",
    "game": "suikoden-ii",
    "order": 1,
    "name": "Hero",
    "characterType": "Combat",
    "recruitment": "Playable from the start of the game",
    "rune": "Bright Shield Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/001-hero.png"
  },
  {
    "id": "nanami",
    "game": "suikoden-ii",
    "order": 2,
    "name": "Nanami",
    "characterType": "Combat",
    "recruitment": "Automatically joins after escaping the Execution Grounds in Kyaro. If not saved in Kyaro, joins automatically after being denied entry to Muse City following the destruction of the Mercenary Fortress.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/002-nanami.png"
  },
  {
    "id": "tsai",
    "game": "suikoden-ii",
    "order": 3,
    "name": "Tsai",
    "characterType": "Combat",
    "recruitment": "After Toto village is destroyed, you are sent to Tsai's house near Ryube Village Forest to bring him to the Mercenary Fortress. He joins when you speak to him.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/003-tsai.png"
  },
  {
    "id": "hanna",
    "game": "suikoden-ii",
    "order": 4,
    "name": "Hanna",
    "characterType": "Combat",
    "recruitment": "Return to Toto after recruiting Apple and speak with her.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/004-hanna.png"
  },
  {
    "id": "anita",
    "game": "suikoden-ii",
    "order": 5,
    "name": "Anita",
    "characterType": "Combat",
    "recruitment": "Anita appears in the tavern at Muse City, or the Inn at Bana Village. Speak to her several times, and try to meet her requests and flatter her. Eventually, she will become available to recruit. Alternatively, speaking with her in the inn at Bana Village with Valeria in her party will make her available.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/005-anita.png"
  },
  {
    "id": "viktor",
    "game": "suikoden-ii",
    "order": 6,
    "name": "Viktor",
    "characterType": "Combat",
    "recruitment": "Joins your party before meeting with Granmeyer.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/006-viktor.png"
  },
  {
    "id": "flik",
    "game": "suikoden-ii",
    "order": 7,
    "name": "Flik",
    "characterType": "Combat",
    "recruitment": "Joins your party before meeting with Granmeyer.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/007-flik.png"
  },
  {
    "id": "freed-yamamoto",
    "game": "suikoden-ii",
    "order": 8,
    "name": "Freed Yamamoto",
    "characterType": "Combat",
    "recruitment": "Joins your party after meeting with Granmeyer.",
    "rune": "Lightning Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/008-freed-yamamoto.png"
  },
  {
    "id": "shu",
    "game": "suikoden-ii",
    "order": 9,
    "name": "Shu",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after defeating Solon Jhee's army.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/009-shu.png"
  },
  {
    "id": "luc",
    "game": "suikoden-ii",
    "order": 10,
    "name": "Luc",
    "characterType": "Combat",
    "recruitment": "Joins your party after defeating Solon Jhee's army.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/010-luc.png"
  },
  {
    "id": "tai-ho",
    "game": "suikoden-ii",
    "order": 11,
    "name": "Tai Ho",
    "characterType": "Combat",
    "recruitment": "Agree to take Fitcher to Two River city, then win 5000 Potch from him in Chinchirorin",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/011-tai-ho.png"
  },
  {
    "id": "yam-koo",
    "game": "suikoden-ii",
    "order": 12,
    "name": "Yam Koo",
    "characterType": "Non-Combat",
    "recruitment": "Joins alongside Tai Ho at Kuskus.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/012-yam-koo.png"
  },
  {
    "id": "ridley-wizen",
    "game": "suikoden-ii",
    "order": 13,
    "name": "Ridley Wizen",
    "characterType": "Non-Combat",
    "recruitment": "Joins the Party after saving Two River City.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/013-ridley-wizen.png"
  },
  {
    "id": "boris-wizen",
    "game": "suikoden-ii",
    "order": 14,
    "name": "Boris Wizen",
    "characterType": "Non-Combat",
    "recruitment": "Boris will take Ridley's place if you run away with Nanami after beating the Neclord",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/014-boris-wizen.png"
  },
  {
    "id": "fitcher",
    "game": "suikoden-ii",
    "order": 15,
    "name": "Fitcher",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after saving Two River City.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/015-fitcher.png"
  },
  {
    "id": "chaco",
    "game": "suikoden-ii",
    "order": 16,
    "name": "Chaco",
    "characterType": "Combat",
    "recruitment": "Joins the Party after saving Two River City.",
    "rune": "-",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/016-chaco.png"
  },
  {
    "id": "hix",
    "game": "suikoden-ii",
    "order": 17,
    "name": "Hix",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, speak with Hix and Tengaar at the inn in Lakewest, then go to Kobold Village to help Hix.",
    "rune": "Exertion Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/017-hix.png"
  },
  {
    "id": "tengaar",
    "game": "suikoden-ii",
    "order": 18,
    "name": "Tengaar",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, speak with Hix and Tengaar at the inn in Lakewest, then go to Kobold Village to help Hix.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/018-tengaar.png"
  },
  {
    "id": "yoshino-yamamoto",
    "game": "suikoden-ii",
    "order": 19,
    "name": "Yoshino Yamamoto",
    "characterType": "Combat",
    "recruitment": "Speak to her in Radat with Freed Yamamoto in your party.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/019-yoshino-yamamoto.png"
  },
  {
    "id": "stallion",
    "game": "suikoden-ii",
    "order": 20,
    "name": "Stallion",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, you can challenge Stallion to a race in Radat after having ran away from battles 50 times.",
    "rune": "None",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/020-stallion.png"
  },
  {
    "id": "clive",
    "game": "suikoden-ii",
    "order": 21,
    "name": "Clive",
    "characterType": "Combat",
    "recruitment": "Speak to Elza in Muse city and take the items from her and leave for the boat. After she and Clive duel, you can speak to Clive to recruit him after having been on the boat.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/021-clive.png"
  },
  {
    "id": "teresa-wisemail",
    "game": "suikoden-ii",
    "order": 22,
    "name": "Teresa Wisemail",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after escaping from Greenhill.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/022-teresa-wisemail.png"
  },
  {
    "id": "nina",
    "game": "suikoden-ii",
    "order": 23,
    "name": "Nina",
    "characterType": "Combat",
    "recruitment": "Joins the party after escaping Greenhill.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/023-nina.png"
  },
  {
    "id": "humphrey-mintz",
    "game": "suikoden-ii",
    "order": 24,
    "name": "Humphrey Mintz",
    "characterType": "Combat",
    "recruitment": "Speak to Humphrey at the inn at Highway Village. Spend the night, and return to accept his quest.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/024-humphrey-mintz.png"
  },
  {
    "id": "kiba-windamier",
    "game": "suikoden-ii",
    "order": 25,
    "name": "Kiba Windamier",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after defeating his army.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/025-kiba-windamier.png"
  },
  {
    "id": "valeria",
    "game": "suikoden-ii",
    "order": 26,
    "name": "Valeria",
    "characterType": "Combat",
    "recruitment": "Select her as the General during your meeting with President Lepant.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/026-valeria.png"
  },
  {
    "id": "tomo",
    "game": "suikoden-ii",
    "order": 27,
    "name": "Tomo",
    "characterType": "Combat",
    "recruitment": "At Castle Level 3, speak to Tsai and have him in your party, then follow him to his house.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/027-tomo.png"
  },
  {
    "id": "feather",
    "game": "suikoden-ii",
    "order": 28,
    "name": "Feather",
    "characterType": "Combat",
    "recruitment": "Bring one of Badeaux's Listening Crystals to the Forest Village, and use it after defeating the Griffins.",
    "rune": "Shining Wind Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/028-feather.png"
  },
  {
    "id": "sigfried",
    "game": "suikoden-ii",
    "order": 29,
    "name": "Sigfried",
    "characterType": "Combat",
    "recruitment": "Place a pure maiden in your party, and use Badeaux's Listening Crystal at the Path of the Unicorn.",
    "rune": "White Saint Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/029-sigfried.png"
  },
  {
    "id": "sierra-mikain",
    "game": "suikoden-ii",
    "order": 30,
    "name": "Sierra Mikain",
    "characterType": "Combat",
    "recruitment": "Defeat the Neclord.",
    "rune": "Thunder Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/030-sierra-mikain.png"
  },
  {
    "id": "hauser",
    "game": "suikoden-ii",
    "order": 31,
    "name": "Hauser",
    "characterType": "Combat",
    "recruitment": "Defeat the Neclord.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/031-hauser.png"
  },
  {
    "id": "jess",
    "game": "suikoden-ii",
    "order": 32,
    "name": "Jess",
    "characterType": "Non-Combat",
    "recruitment": "Accept Jess's Apology after defeating the Neclord",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/032-jess.png"
  },
  {
    "id": "georg-prime",
    "game": "suikoden-ii",
    "order": 33,
    "name": "Georg Prime",
    "characterType": "Combat",
    "recruitment": "성 레벨 3 이후 네크로드를 격파하고 용구마을과 코코마을 사이 산길에서 게오르그에게 말을 걸면 합류합니다.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/033-georg-prime.png"
  },
  {
    "id": "killey",
    "game": "suikoden-ii",
    "order": 34,
    "name": "Killey",
    "characterType": "Combat",
    "recruitment": "At Castle Level 3, tell Killey about Alex in South Window, then speak to Alex at Headquarters, and return to South Window before repeatedly asking Killey to join.",
    "rune": "-",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/034-killey.png"
  },
  {
    "id": "pesmerga",
    "game": "suikoden-ii",
    "order": 35,
    "name": "Pesmerga",
    "characterType": "Combat",
    "recruitment": "At Castle Level 4, speak to Pesmerga at the end of the Cave of the Wind",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/035-pesmerga.png"
  },
  {
    "id": "abizboah",
    "game": "suikoden-ii",
    "order": 36,
    "name": "Abizboah",
    "characterType": "Combat",
    "recruitment": "At Castle Level 3 or up, use the Listening Orb at the Tinto Mines to speak to and recruit Abizboah and his family.",
    "rune": "Blue Drop Rune",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/036-abizboah.png"
  },
  {
    "id": "mukumuku",
    "game": "suikoden-ii",
    "order": 37,
    "name": "Mukumuku",
    "characterType": "Combat",
    "recruitment": "After escaping from the Mercenary Fortress, examine the tree behind the dojo in Kyaro Town three times to have them join the group. Alternatively, you can befriend them around Greenhill City using the same method as the other Squirrel Squads.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/037-mukumuku.png"
  },
  {
    "id": "rikimaru",
    "game": "suikoden-ii",
    "order": 38,
    "name": "Rikimaru",
    "characterType": "Combat",
    "recruitment": "Speak with him in Ryube and agree to pay for his meal. If missed in Ryube, speak with him in Coronet after Ryube's destruction and agree to cover his meal.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/038-rikimaru.png"
  },
  {
    "id": "millie",
    "game": "suikoden-ii",
    "order": 39,
    "name": "Millie",
    "characterType": "Combat",
    "recruitment": "Speak with her in Ryube and agree to assist in finding Bonaparte.",
    "rune": "Groundhog Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/039-millie.png"
  },
  {
    "id": "kinnison",
    "game": "suikoden-ii",
    "order": 40,
    "name": "Kinnison",
    "characterType": "Combat",
    "recruitment": "Locate the bird's nest in Ryube Forest and return it to the tree. Leave the forest and come back to the same spot after a few minutes.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/040-kinnison.png"
  },
  {
    "id": "shiro",
    "game": "suikoden-ii",
    "order": 41,
    "name": "Shiro",
    "characterType": "Combat",
    "recruitment": "Locate the bird's nest in Ryube Forest and return it to the tree. Leave the forest and come back to the same spot after a few minutes, Shiro and Kinnison will be here.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/041-shiro.png"
  },
  {
    "id": "zamza",
    "game": "suikoden-ii",
    "order": 42,
    "name": "Zamza",
    "characterType": "Combat",
    "recruitment": "Speak with him in Toto with Nanami in your active party, or speak with him in South Window with Nanami in your active party (after defeating Solon Jhee's army, if missed in Toto).",
    "rune": "Fire Dragon Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/042-zamza.png"
  },
  {
    "id": "apple",
    "game": "suikoden-ii",
    "order": 43,
    "name": "Apple",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after discovering that Toto Village has been destroyed.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/043-apple.png"
  },
  {
    "id": "tuta",
    "game": "suikoden-ii",
    "order": 44,
    "name": "Tuta",
    "characterType": "Combat",
    "recruitment": "After the fall of the Mercenary Fortress, speak with him in Muse City and he will join the team.",
    "rune": "Medicine Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/044-tuta.png"
  },
  {
    "id": "gilbert",
    "game": "suikoden-ii",
    "order": 45,
    "name": "Gilbert",
    "characterType": "Non-Combat",
    "recruitment": "During the War event in Muse, damage his army unit.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/045-gilbert.png"
  },
  {
    "id": "eilie",
    "game": "suikoden-ii",
    "order": 46,
    "name": "Eilie",
    "characterType": "Combat",
    "recruitment": "Joins your party in Coronet after defeating Tai Ho in Chinchirorin.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/046-eilie.png"
  },
  {
    "id": "rina",
    "game": "suikoden-ii",
    "order": 47,
    "name": "Rina",
    "characterType": "Combat",
    "recruitment": "Joins your party in Coronet after defeating Tai Ho in Chinchirorin.",
    "rune": "-",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/047-rina.png"
  },
  {
    "id": "bolgan",
    "game": "suikoden-ii",
    "order": 48,
    "name": "Bolgan",
    "characterType": "Combat",
    "recruitment": "Joins your party in Coronet after defeating Tai Ho in Chinchirorin.",
    "rune": "Fire Breath Rune",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/048-bolgan.png"
  },
  {
    "id": "leona",
    "game": "suikoden-ii",
    "order": 49,
    "name": "Leona",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after defeating Solon Jhee's army.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/049-leona.png"
  },
  {
    "id": "gengen",
    "game": "suikoden-ii",
    "order": 50,
    "name": "Gengen",
    "characterType": "Combat",
    "recruitment": "Joins your party after returning from Kyaro.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/050-gengen.png"
  },
  {
    "id": "barbara",
    "game": "suikoden-ii",
    "order": 51,
    "name": "Barbara",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after defeating Solon Jhee's army.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/051-barbara.png"
  },
  {
    "id": "huan",
    "game": "suikoden-ii",
    "order": 52,
    "name": "Huan",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after defeating Solon Jhee's army.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/052-huan.png"
  },
  {
    "id": "oulan",
    "game": "suikoden-ii",
    "order": 53,
    "name": "Oulan",
    "characterType": "Combat",
    "recruitment": "Enter Kuskus with a party comprised of women, and speak with the woman near the entrance to gain access.",
    "rune": "Angry Dragon Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/053-oulan.png"
  },
  {
    "id": "taki",
    "game": "suikoden-ii",
    "order": 54,
    "name": "Taki",
    "characterType": "Non-Combat",
    "recruitment": "Speak with her repeatedly in Lakewest.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/054-taki.png"
  },
  {
    "id": "hans",
    "game": "suikoden-ii",
    "order": 55,
    "name": "Hans",
    "characterType": "Non-Combat",
    "recruitment": "He is in an Inn at Two River City. Players can speak to him and allow him to set up an Armor Shop at the castle",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/055-hans.png"
  },
  {
    "id": "tetsu",
    "game": "suikoden-ii",
    "order": 56,
    "name": "Tetsu",
    "characterType": "Non-Combat",
    "recruitment": "Use a Fried Taco from Kobold Village on one of your members, then speak to him at Lakewest.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/056-tetsu.png"
  },
  {
    "id": "hai-yo",
    "game": "suikoden-ii",
    "order": 57,
    "name": "Hai Yo",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, speak to him in the kitchen at Headquarters.",
    "rune": "-",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/057-hai-yo.png"
  },
  {
    "id": "richmond",
    "game": "suikoden-ii",
    "order": 58,
    "name": "Richmond",
    "characterType": "Non-Combat",
    "recruitment": "Accept his challenge in Radat and lose the coin toss. After that, enter the restaurant and speak to the customer near the door. Then, speak to Richmond and ask him to use the coin you obtained.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/058-richmond.png"
  },
  {
    "id": "amada",
    "game": "suikoden-ii",
    "order": 59,
    "name": "Amada",
    "characterType": "Combat",
    "recruitment": "Agree to take Fitcher to Two River city, then defeat Amada in a duel to recruit him.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/059-amada.png"
  },
  {
    "id": "alex",
    "game": "suikoden-ii",
    "order": 60,
    "name": "Alex",
    "characterType": "Non-Combat",
    "recruitment": "Speak with Alex on the second floor at the inn in South Window.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/060-alex.png"
  },
  {
    "id": "hilda",
    "game": "suikoden-ii",
    "order": 61,
    "name": "Hilda",
    "characterType": "Non-Combat",
    "recruitment": "Hilda joins alongside Alex at South Window",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/061-hilda.png"
  },
  {
    "id": "adlai",
    "game": "suikoden-ii",
    "order": 62,
    "name": "Adlai",
    "characterType": "Non-Combat",
    "recruitment": "In South Window, bring a Wooden Shield, Sacrificial Jizo, and a Wind Rune, then throw the wind rune at him.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/062-adlai.png"
  },
  {
    "id": "emilia",
    "game": "suikoden-ii",
    "order": 63,
    "name": "Emilia",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 2, reveal your identity to her after the tour of the academy in Greenhill.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/063-emilia.png"
  },
  {
    "id": "gabocha",
    "game": "suikoden-ii",
    "order": 64,
    "name": "Gabocha",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, speak to him at Two River City with Gengen in your party.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/064-gabocha.png"
  },
  {
    "id": "sid",
    "game": "suikoden-ii",
    "order": 65,
    "name": "Sid",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, enter Sid's room in Two River City with Chaco in your party.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/065-sid.png"
  },
  {
    "id": "jeane",
    "game": "suikoden-ii",
    "order": 66,
    "name": "Jeane",
    "characterType": "Non-Combat",
    "recruitment": "After the quest in Greenhill City, make sure your Castle Level is 2 and speak with Jeane at the Rune Shop at Two River City.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/066-jeane.png"
  },
  {
    "id": "shilo",
    "game": "suikoden-ii",
    "order": 67,
    "name": "Shilo",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, win 5000 Potch in Chinchirorin.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/067-shilo.png"
  },
  {
    "id": "yuzu",
    "game": "suikoden-ii",
    "order": 68,
    "name": "Yuzu",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 2, make sure Hix and Tengaar are already recruited, and help her find three sheep at Kobold Village after the quest in Greenhill. Allow her to stay at your headquarters.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/068-yuzu.png"
  },
  {
    "id": "shin",
    "game": "suikoden-ii",
    "order": 69,
    "name": "Shin",
    "characterType": "Combat",
    "recruitment": "Joins the party after escaping Greenhill.",
    "rune": "Spider Slay Rune",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/069-shin.png"
  },
  {
    "id": "meg",
    "game": "suikoden-ii",
    "order": 70,
    "name": "Meg",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, speak to Meg at the Muse.",
    "rune": "Gadget Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/070-meg.png"
  },
  {
    "id": "gadget",
    "game": "suikoden-ii",
    "order": 71,
    "name": "Gadget",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, speak to Meg at the Muse and Gadget will join alongside her.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/071-gadget.png"
  },
  {
    "id": "wakaba",
    "game": "suikoden-ii",
    "order": 72,
    "name": "Wakaba",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, make sure the main character is above level 30, and speak to her in the Forest Village.",
    "rune": "White Tiger Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/072-wakaba.png"
  },
  {
    "id": "tony",
    "game": "suikoden-ii",
    "order": 73,
    "name": "Tony",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 2, speak to him twice in the Elder's House at the Forest Village.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/073-tony.png"
  },
  {
    "id": "viki",
    "game": "suikoden-ii",
    "order": 74,
    "name": "Viki",
    "characterType": "Combat",
    "recruitment": "Viki appears on the Forest Path to Matilda. Speak with her and agree to let her stay at your house.",
    "rune": "Blinking Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/074-viki.png"
  },
  {
    "id": "futch",
    "game": "suikoden-ii",
    "order": 75,
    "name": "Futch",
    "characterType": "Combat",
    "recruitment": "Joins your party alongside Humphrey at Highway Village.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/075-futch.png"
  },
  {
    "id": "miklotov",
    "game": "suikoden-ii",
    "order": 76,
    "name": "Miklotov",
    "characterType": "Combat",
    "recruitment": "Joins your party after the quest in Rockaxe.",
    "rune": "Knight Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/076-miklotov.png"
  },
  {
    "id": "camus",
    "game": "suikoden-ii",
    "order": 77,
    "name": "Camus",
    "characterType": "Combat",
    "recruitment": "Joins your party after the quest in Rockaxe.",
    "rune": "Rage Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/077-camus.png"
  },
  {
    "id": "klaus-windamier",
    "game": "suikoden-ii",
    "order": 78,
    "name": "Klaus Windamier",
    "characterType": "Non-Combat",
    "recruitment": "Automatically recruited after defeating Kiba's Army",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/078-klaus-windamier.png"
  },
  {
    "id": "kasumi",
    "game": "suikoden-ii",
    "order": 79,
    "name": "Kasumi",
    "characterType": "Combat",
    "recruitment": "Select her as the General during your meeting with President Lepant.",
    "rune": "Shrike Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/079-kasumi.png"
  },
  {
    "id": "sheena",
    "game": "suikoden-ii",
    "order": 80,
    "name": "Sheena",
    "characterType": "Combat",
    "recruitment": "Joins the player automatically after speaking with President Lepant.",
    "rune": "-",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/080-sheena.png"
  },
  {
    "id": "gordon",
    "game": "suikoden-ii",
    "order": 81,
    "name": "Gordon",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, speak to Gordon in Gregminster to accept his quest and make a total of 50,000 potch from trading. Speaking to him again will allow you to recruit him.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/081-gordon.png"
  },
  {
    "id": "lorelai",
    "game": "suikoden-ii",
    "order": 82,
    "name": "Lorelai",
    "characterType": "Combat",
    "recruitment": "At Castle Level 3, speak to Lorelai at Gregminster.",
    "rune": "-",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/082-lorelai.png"
  },
  {
    "id": "sasuke",
    "game": "suikoden-ii",
    "order": 83,
    "name": "Sasuke",
    "characterType": "Combat",
    "recruitment": "If you recruited Valeria, Sasuke joins automatically after recruiting Mondo. If you recruited Kasumi, you will have to speak to Sasuke near Rokkaku's trading post with Kasumi in your party.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/083-sasuke.png"
  },
  {
    "id": "mondo",
    "game": "suikoden-ii",
    "order": 84,
    "name": "Mondo",
    "characterType": "Combat",
    "recruitment": "In rokkaku, go to the fourth screen in the Forest Path to Gregminster to find the hidden entrance. Hanzo will order Mondo to join your party. You can recruit him at Castle Level 3 if you recruited Kasumi, and Castle Level 4 if you recruited Valeria.",
    "rune": "Mayfly Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/084-mondo.png"
  },
  {
    "id": "templeton",
    "game": "suikoden-ii",
    "order": 85,
    "name": "Templeton",
    "characterType": "Non-Combat",
    "recruitment": "Receive a mission from Jess, and find him at the Mercenary Fortress. Follow him to Toto and you can recruit him.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/085-templeton.png"
  },
  {
    "id": "badeaux",
    "game": "suikoden-ii",
    "order": 86,
    "name": "Badeaux",
    "characterType": "Combat",
    "recruitment": "Have an animal in your party and speak to him at the Forest Path to Matilda.",
    "rune": "Howling Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/086-badeaux.png"
  },
  {
    "id": "ayda",
    "game": "suikoden-ii",
    "order": 87,
    "name": "Ayda",
    "characterType": "Combat",
    "recruitment": "Joins the player alongside feather in Forest Village",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/087-ayda.png"
  },
  {
    "id": "connell",
    "game": "suikoden-ii",
    "order": 88,
    "name": "Connell",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, bring a Sound Set with you and speak to Connell at the Forest Village.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/088-connell.png"
  },
  {
    "id": "karen",
    "game": "suikoden-ii",
    "order": 89,
    "name": "Karen",
    "characterType": "Combat",
    "recruitment": "After defeating Luca Blight and getting your Castle Level to 3, go to the inn at Kuskus and agree to dance with her.",
    "rune": "None",
    "runeSlots": "4",
    "image": "/characters/suikoden-ii/089-karen.png"
  },
  {
    "id": "maximillian",
    "game": "suikoden-ii",
    "order": 90,
    "name": "Maximillian",
    "characterType": "Non-Combat",
    "recruitment": "After defeating Luca Blight and getting your Castle Level to 3, speak to him at South Window.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/090-maximillian.png"
  },
  {
    "id": "raura",
    "game": "suikoden-ii",
    "order": 91,
    "name": "Raura",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, recruit Jeane, and speak to Raura at Tinto.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/091-raura.png"
  },
  {
    "id": "kahn-marley",
    "game": "suikoden-ii",
    "order": 92,
    "name": "Kahn Marley",
    "characterType": "Combat",
    "recruitment": "Defeat the Neclord.",
    "rune": "None",
    "runeSlots": "4",
    "image": "/characters/suikoden-ii/092-kahn-marley.png"
  },
  {
    "id": "tenkou",
    "game": "suikoden-ii",
    "order": 93,
    "name": "Tenkou",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, bring Tenkou a Window Set at Crom.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/093-tenkou.png"
  },
  {
    "id": "long-chan-chan",
    "game": "suikoden-ii",
    "order": 94,
    "name": "Long Chan-Chan",
    "characterType": "Combat",
    "recruitment": "At Castle Level 2, go to the inn at Crom with Wakaba in your party and speak to Long Chan-Chan.",
    "rune": "White Tiger Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/094-long-chan-chan.png"
  },
  {
    "id": "gijimu",
    "game": "suikoden-ii",
    "order": 95,
    "name": "Gijimu",
    "characterType": "Combat",
    "recruitment": "Defeat the Neclord.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/095-gijimu.png"
  },
  {
    "id": "lo-wen",
    "game": "suikoden-ii",
    "order": 96,
    "name": "Lo Wen",
    "characterType": "Combat",
    "recruitment": "Defeat the Neclord.",
    "rune": "-",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/096-lo-wen.png"
  },
  {
    "id": "koyu",
    "game": "suikoden-ii",
    "order": 97,
    "name": "Koyu",
    "characterType": "Combat",
    "recruitment": "Defeat the Neclord.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/097-koyu.png"
  },
  {
    "id": "marlowe",
    "game": "suikoden-ii",
    "order": 98,
    "name": "Marlowe",
    "characterType": "Non-Combat",
    "recruitment": "Defeat the Neclord.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/098-marlowe.png"
  },
  {
    "id": "lebrante",
    "game": "suikoden-ii",
    "order": 99,
    "name": "Lebrante",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, bring Lebrante a Celadon Urn at Radat.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/099-lebrante.png"
  },
  {
    "id": "simone-verdricci",
    "game": "suikoden-ii",
    "order": 100,
    "name": "Simone Verdricci",
    "characterType": "Combat",
    "recruitment": "At Castle Level 3, speak to him at the Sluice Gate in Radat holding a Rose Brooch in your inventory.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/100-simone-verdricci.png"
  },
  {
    "id": "hoi",
    "game": "suikoden-ii",
    "order": 101,
    "name": "Hoi",
    "characterType": "Combat",
    "recruitment": "At Castle Level 3, speak to him at the restaurant in Radat. He will be available to recruit after defeating Luca.",
    "rune": "Technique Rune",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/101-hoi.png"
  },
  {
    "id": "gantetsu",
    "game": "suikoden-ii",
    "order": 102,
    "name": "Gantetsu",
    "characterType": "Combat",
    "recruitment": "At Castle Level 3, speak to Gantetsu at South Window after defeating a Neclord and defeat him in a pushing contest. Your party must have a combined strength of 400.",
    "rune": "-",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/102-gantetsu.png"
  },
  {
    "id": "annallee",
    "game": "suikoden-ii",
    "order": 103,
    "name": "Annallee",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, speak to Annallee at the inn in South Window, then speak to her at City Hall and listen to her song.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/103-annallee.png"
  },
  {
    "id": "bob",
    "game": "suikoden-ii",
    "order": 104,
    "name": "Bob",
    "characterType": "Combat",
    "recruitment": "With at least 80 recruits, speak to Bob in Two River City.",
    "rune": "Rabid Fang Rune",
    "runeSlots": "2",
    "image": "/characters/suikoden-ii/104-bob.png"
  },
  {
    "id": "jude",
    "game": "suikoden-ii",
    "order": 105,
    "name": "Jude",
    "characterType": "Non-Combat",
    "recruitment": "Speak with Jude at the New Leaf Academy, then head to Forest Village to get clay from a villager, before travelling back to give it to Jude.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/105-jude.png"
  },
  {
    "id": "pico",
    "game": "suikoden-ii",
    "order": 106,
    "name": "Pico",
    "characterType": "Non-Combat",
    "recruitment": "After Recruiting Annallee and getting Castle Level 3, speak with Pico at the Armor Shop at Tinto.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/106-pico.png"
  },
  {
    "id": "alberto",
    "game": "suikoden-ii",
    "order": 107,
    "name": "Alberto",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, make sure you've recruited Annallee and Pico. Then, speak to him in the Armor Shop at Tinto and speak about Annallee.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/107-alberto.png"
  },
  {
    "id": "tessai",
    "game": "suikoden-ii",
    "order": 108,
    "name": "Tessai",
    "characterType": "Non-Combat",
    "recruitment": "At Castle Level 3, place Viktor in your party and speak to Tessai at the Blacksmith after liberating Greenhill.",
    "rune": "-",
    "runeSlots": "-",
    "image": "/characters/suikoden-ii/108-tessai.png"
  },
  {
    "id": "genshu",
    "game": "suikoden-ii",
    "order": 109,
    "name": "Genshu",
    "characterType": "Combat",
    "recruitment": "At Castle Level 4, equip a party member with a Lv. 14 weapon and take the boat from Kuskus to Coronet and speak with Genshu.",
    "rune": "Swallow Rune",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/109-genshu.png"
  },
  {
    "id": "vincent",
    "game": "suikoden-ii",
    "order": 110,
    "name": "Vincent",
    "characterType": "Combat",
    "recruitment": "At Castle Level 4, put Simone in your party and speak with Vincent at the Sluice Gate in Radat.",
    "rune": "-",
    "runeSlots": "1",
    "image": "/characters/suikoden-ii/110-vincent.png"
  },
  {
    "id": "mazus",
    "game": "suikoden-ii",
    "order": 111,
    "name": "Mazus",
    "characterType": "Combat",
    "recruitment": "Speak to Mazus in the Tinto Mines at Castle Level 4.",
    "rune": "None",
    "runeSlots": "3",
    "image": "/characters/suikoden-ii/111-mazus.png"
  }
] as const;
